### ISSUE TITLE
Nested exception is not accessible via `std::rethrow_if_nested`

### ISSUE THREAD

**Issue by OzanCansel** [hazelcast/hazelcast-cpp-client#1054]
C++ compiler version: GCC 11.3.0
Hazelcast Cpp client version: 5.0.0
Hazelcast server version: -
Number of the clients: -
Cluster size, i.e. the number of Hazelcast cluster members:
OS version (Windows/Linux/OSX):
Ubuntu 22.04 (Boost version is 1.76.0)

Please attach relevant logs and files for client and server side.

#### Expected behaviour
Nested exception should be accessible via `std::rethrow_if_nested`.

#### Actual behaviour
`std::rethrow_if_nested` doesn't throw the inner exception.

#### Steps to reproduce the behaviour
Take a look at [here](https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/test/src/HazelcastTests7.cpp#L1868-L1874)

Run `cloud_discovery_test.token_should_not_be_leaked` and `std::rethrow_if_nested` doesn't throw anything.

**Comment by akeles85** [comment]
This is a framework future and we could not a proper solution for this. 
https://hazelcast.atlassian.net/browse/API-1792
