### ISSUE TITLE
IssueTest.testOperationRedo_smartRoutingDisabled crashes occasionally on github actions. [API-1807]

### ISSUE THREAD

**Issue by OzanCansel** [hazelcast/hazelcast-cpp-client#1069]
C++ compiler version: msvc-14.2
Hazelcast Cpp client version: 5.0.0
Hazelcast server version: 5.1.3
Number of the clients: -
Cluster size, i.e. the number of Hazelcast cluster members: -
OS version (Windows/Linux/OSX):
Windows

#### Expected behaviour
Pass test

#### Actual behaviour
Crashes on the test.

#### Steps to reproduce the behaviour
It might be a different test but this is what I suspected.
Here is the [link](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/3784657210/jobs/6434121863).
[IssueTest.testOperationRedo_smartRoutingDisabled.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/10313037/IssueTest.testOperationRedo_smartRoutingDisabled.txt)

**Comment by ihsandemir** [comment]
fixed by https://github.com/hazelcast/hazelcast-cpp-client/pull/1104
