### ISSUE TITLE
ReliableTopicTest.testAlwaysStartAfterTail crashes occassionally on github actions. [API-1815]

### ISSUE THREAD

**Issue by OzanCansel** [hazelcast/hazelcast-cpp-client#1078]
C++ compiler version: vc 14.1
Hazelcast Cpp client version: 5.1.0
Hazelcast server version: 5.1.3
Number of the clients:
Cluster size, i.e. the number of Hazelcast cluster members:
OS version (Windows/Linux/OSX):
Windows

Please attach relevant logs and files for client and server side.

#### Expected behaviour
Pass test

#### Actual behaviour
Crashes on test

#### Steps to reproduce the behaviour
Here is the [link](https://github.com/hazelcast/hazelcast-cpp-client/actions/runs/3814810754/jobs/6489383386)
[ReliableTopicTest_testAlwaysStartAfterTail.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/10330378/ReliableTopicTest_testAlwaysStartAfterTail.txt)

**Comment by akeles85** [comment]
Solved with #1087

**Comment by akeles85** [comment]
The solution is tested with multiple times and the error is resolved.
