### ISSUE TITLE
C++ client connection problems when node is powered off

### ISSUE THREAD

**Issue by burakgokmen** [hazelcast/hazelcast-cpp-client#173]
There are several Hazelcast servers running on different nodes in our test environment.

When I power off the node where one of the Hazelcast servers (3.6.2) is running, I occasionally encounter with two problems:

1) The C++ client (3.6.3) might get stuck in printing the following message:
Future.set_exception should not be called twice : details  ExceptionMessage (Wait is timed out) at Future::get(timeInSeconds)

2) The C++ client might get stuck in hazelcast::client::IMap::keySet(). The stack output:
Thread1:
- stlp_std::ostreambuf_iterator...:copy() 
- stlp_std::ostreambuf_iterator...:put_integer() 
- stlp_std::num_put::do_put(...)
- stlp_std::priv::_put_number()
- hazelcast::client::operator<<(...)
- hazelcast::client::connection::CallFuture::get(long)
- hazelcast::client::connection::CallFuture::get()
- hazelcast::client::proxy::ProxyImpl:invoke(...)
- hazelcast::client::proxy::IMapImpl:keySetData(...)
- hazelcast::client::IMap<...>:keySet(...)

Thread3:
- hazelcast::client::Socket:::send()
- hazelcast::client::connection::OutputSocketStream::write()
- hazelcast::client::connection::Connection::init()
- hazelcast::client::connection::ConnectionManager::authenticate()
- hazelcast::client::connection::ConnectionManager::connectTo()
- hazelcast::client::connection::OwnerConnectionFuture::createNew()
- hazelcast::client::connection::ConnectionManager::createOwnerConnection()
- hazelcast::client::spi::ClusterService::connectToOne()
- hazelcast::client::connection::ClusterListenerThread::run()
- hazelcast::client::connection::ClusterListenerThread::staticRun()
- hazelcast::util::Thread::controlledThread()

C++ client connection parameters:
- ClientProperties::PROP_HEARTBEAT_INTERVAL=1
- ClientProperties::PROP_HEARTBEAT_TIMEOUT=2
- ClientProperties::PROP_REQUEST_RETRY_COUNT=0
- ClientProperties::PROP_REQUEST_RETRY_WAIT_TIME=1
- ConnectionTimeout=500
- ConnectionAttemptLimit=0
- AttemptPeriod=0

The OS is RHEL 6.6, the machine is virtual.

**Comment by ihsandemir** [comment]
@burakgokmen Can you set the log level to finest like this ( clientConfig.setLogLevel(FINEST) ) and re-run the test and share your output log here?

**Comment by burakgokmen** [comment]
[hazelcastproblem.tar.gz](https://github.com/hazelcast/hazelcast-cpp-client/files/413184/hazelcastproblem.tar.gz)

**Comment by burakgokmen** [comment]
I have added sample code so that you can generate the problem.

**Comment by ihsandemir** [comment]
Hello Burak,

I have a fix for the client here: https://github.com/hazelcast/hazelcast-cpp-client/pull/174 

Please try with the fixed branch at https://github.com/ihsandemir/hazelcast-cpp-client/tree/futureSetTwiceFix  . The commit is: https://github.com/ihsandemir/hazelcast-cpp-client/commit/4663ea3204a83a2130a68724cf223de430c0750d

In addition please use the following options in hazelcast.xml for server configuration: 
    <properties>
        <property name="hazelcast.max.no.heartbeat.seconds">2</property>
        <property name="hazelcast.heartbeat.interval.seconds">1</property>
    </properties>

These settings allows the other members to detect that the member is not responsive any more (when there is no way to detect it from the connection) Please note that the settings are very aggressive and they may cause false member disconnects. I suggest you to increase these settings at least for the server side, i put the same values as you used for the client setting here.

Please let me know if this solves your problem.

**Comment by burakgokmen** [comment]
In addition please use the following options in hazelcast.xml for server configuration: -> Values 2 and 1 OK, but which server parameters?

**Comment by burakgokmen** [comment]
[main.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/424440/main.zip)

**Comment by burakgokmen** [comment]
The problem about Future.set_exception seems to be solved. I could not reproduce the faulty case with the sample code I've provided before. So thanks.

But there are other problems. I have provided new sample code for producing the case. 

Production of the problem:
1) Start Hazelcast server on two different nodes with the code I have provided before.
2) Start 100 processes using the last provided code on one of the nodes.
3) Power off the other node.

In this case, I observe that some of the threads might get stuck in Socket::send(). Please refer to the stack below. Some of the threads might recover after a while (sometimes in minutes, this is also a problem for our usage), but some of them cannot. Meanwhile some of the threads continue using map without problems. The client parameters we are using might be strict, but all threads use the same connection and some of them are using the map without any problems. So there is not a problem like client disconnection. By the way, I switched to Hazelcast server 3.7.

Socket.:send()
connection::OutputSocketStream::write()
connection::Connection::init()
connection::ConnectionManager::authenticate()
connection::ConnectionManager::connectTo()
connection::ConnectionManager::getOrConnectResolved()
connection::ConnectionManager::getOrConnect()
connection::ConnectionManager::getOrConnect()
connection::ConnectionManager::getRandomConnection()
spi::InvocationService::invokeOnRandomTarget()
proxy::ProxyImpl::invoke()
proxy::IMapImpl::keySetData()
IMap.keySet()

**Comment by ihsandemir** [comment]
Hello Burak,

Thanks for reporting the problem. I examined the code and indeed there is small window where the socket works as blocking (except this window the socket works non-blocking). This window is during connection initiation and authentication phase and this is what you see in your stack trace. I will check to see how we can make the connection initiation and authentication non-blocking as well.

**Comment by bisegni** [comment]
from the last master version i still have the issue, when i stop a node the put or set in an hash table will crash. I have two instance of hazel cast and setter is connected to first(5701) and reader to the second(5702).
this is my write:
` hazelcast::client::ClientConfig config;
    config.addAddress(hazelcast::client::Address("localhost", 5701));
    hazelcast::client::HazelcastClient hz(config);
    
    hazelcast::client::IMap<std::string, int > map = hz.getMap<std::string, int>("uint_map");
    for(int idx = 0;
        idx < 1000000;
        idx++) {
        map.put("key", idx);
        std::cout << idx << std::endl;
        usleep(1000);
    }
    std::cout << "Finished" << std::endl;
`

and this is my reader:
`hazelcast::client::ClientConfig config;
    config.addAddress(hazelcast::client::Address("localhost", 5702));
    hazelcast::client::HazelcastClient hz(config);
    
    hazelcast::client::IMap<std::string, int > map = hz.getMap<std::string, int>("uint_map");
    int counter = 0;
    unsigned int repetition = 0;
    map.clear();
    while(counter < 1000000) {
        boost::shared_ptr<int> result = map.get("key");
        if(result.get()) {
            if(*result == counter) {
                repetition++;
            } else {
                counter = *result+1;
                repetition = 0;
            }
            std::cout << "Received:" << counter << std::endl;
        } else {
            std::cout << "No data received" << std::endl;
        }
        usleep(500);
    }
    std::cout << "Finished with repetition:" << repetition << std::endl;
`

**Comment by ihsandemir** [comment]
fixed by https://github.com/hazelcast/hazelcast-cpp-client/pull/392
