### ISSUE TITLE
getEntryView for non exist value causes hazelcast to crash

### ISSUE THREAD

**Issue by rogi-orion** [hazelcast/hazelcast-cpp-client#177]
The only validation you can do to "getEntryView" is getting the key, and see if the value is not NULL, but if the value is about to expired, then asking the value does not promise that "getEntryView" will not crash the client

another issue with "getEntryView" is that he does not throw an exception so you can't even wrap it with try catch, and it always will crash the client in case it does not exist

**Comment by ihsandemir** [comment]
Hello @rogi-orion ,

You are correct, there is a problem with IMap.getEntryView but RawPointerMap.getEntryView interface is better for handling null returning calls. I will submit a PR that does a minor fix for the RawPointerMap.getEntryView so that it returns a null pointer for cases where the server returned null and the user can check for null. If possible, I suggest using RawPointerMap rather than IMap.

Just to clarify that I understood your point correctly is it possible that you can send a test code to make sure we are on the same page?

**Comment by ihsandemir** [comment]
I added a test and a fix for handling this case: https://github.com/hazelcast/hazelcast-cpp-client/pull/178

Just make sure that you use RawPointerMap interface. Here is how you can use it: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/manual/src/CPlusClient.md RawPointerAPI section.

**Comment by rogi-orion** [comment]
FYI, the specific use case is hard to create, but not impossible, but just asking for any key event view that does not exist will crash the client. so I don't have a sample code, but the use case is quite simple to reproduce

also I'm using the 3.6.2 version

**Comment by ihsandemir** [comment]
Ok, my fix and suggestion should help solve your problem.

**Comment by rogi-orion** [comment]
thanks!

**Comment by ihsandemir** [comment]
@rogi-orion I merged the PR, can you try with the head snapshot and let me know if the fix works for you?

**Comment by rogi-orion** [comment]
can build:

In file included from /home/third/HazelcastClient/hazelcast/src/hazelcast/client/protocol/ClientExceptionFactory.cpp:23:
/home/third/HazelcastClient/hazelcast/include/hazelcast/client/protocol/ClientExceptionFactory.h:42: error: expected unqualified-id before ‘&’ token
/home/third/HazelcastClient/hazelcast/include/hazelcast/client/protocol/ClientExceptionFactory.h:42: error: expected ‘)’ before ‘&’ token
/home/third/HazelcastClient/hazelcast/include/hazelcast/client/protocol/ClientExceptionFactory.h:42: error: expected ‘;’ before ‘&’ token
[ 28%] Building CXX object CMakeFiles/HazelcastClient3.7-SNAPSHOT_64.dir/hazelcast/src/hazelcast/client/protocol/UsernamePasswordCredentials.cpp.o
/home/third/HazelcastClient/hazelcast/src/hazelcast/client/protocol/ClientExceptionFactory.cpp: In member function ‘std::auto_ptr<hazelcast::client::exception::IException> hazelcast::client::protocol::ClientExceptionFactory::createException(hazelcast::client::protocol::ClientMessage&) const’:
/home/third/HazelcastClient/hazelcast/src/hazelcast/client/protocol/ClientExceptionFactory.cpp:139: error: ‘class hazelcast::client::protocol::ExceptionFactory’ has no member named ‘createException’
make[2]: *** [CMakeFiles/HazelcastClient3.7-SNAPSHOT_64.dir/hazelcast/src/hazelcast/client/protocol/ClientExceptionFactory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/HazelcastClient3.7-SNAPSHOT_64.dir/all] Error 2
make: *** [all] Error 2

**Comment by ihsandemir** [comment]
are you using from master head? What is your compiler and version?

Try putting including <string> .

**Comment by rogi-orion** [comment]
I might not have the right tools to build this, it needs CMake 3.1 while I have 2.8, so I might just download the release zip, and used the so files and headers.

**Comment by ihsandemir** [comment]
I can send you a library zip if you would like to try. Are you using Linux 64-bit?

**Comment by rogi-orion** [comment]
that will be great, and yes, I do use linux 64-bit

**Comment by rogi-orion** [comment]
@ihsandemir , did you manage to build the version? and if you did, can you upload it a one of the file share services?

**Comment by ihsandemir** [comment]
Hello @rogi-orion Here is the snapshot build: https://drive.google.com/file/d/0B465urP0EmqMYWpKVlJLcW91eU0/view?usp=sharing

Try it and let me know if it works for you.

Regards,
ihsan

**Comment by rogi-orion** [comment]
thanks, I'll try reproduce this.

**Comment by rogi-orion** [comment]
closed the case by mistake, sorry.

**Comment by ihsandemir** [comment]
Since RawPointerMap api is released, this issue can be closed.
