### ISSUE TITLE
Remove seperate owner connection

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-cpp-client#18]
Our other clients opens one connection to a node in cluster. Only C++ opens two connections two owner node. C++ code base needs to be updated and should be sync with other clients. 

Also related code written to preserve backward compatibility on server side. (Client HeartBeat check ) 
should be updated accordingly after the fix.

Related issue leads to fix on server side https://github.com/hazelcast/hazelcast/issues/5054
Related change on master https://github.com/hazelcast/hazelcast/pull/7252
Related change on maintenance https://github.com/hazelcast/hazelcast/pull/7253

**Comment by ihsandemir** [comment]
fixed by https://github.com/hazelcast/hazelcast-cpp-client/pull/392
