### ISSUE TITLE
variable m has initializer but incomplete type Error

### ISSUE THREAD

**Issue by gauthamu** [hazelcast/hazelcast-cpp-client#195]
Trying the below code ins Client 3.6.3 stable version, during compilation below code:
`hazelcast::client::IMap<std::string, std::string> m = hz.getMap<std::string, std::string>("map");
hazelcast::client::adaptor::RawPointerMap<std::string, std::string> map(m);`

variable m has initializer but incomplete type error is thrown any reason why this happens?

**Comment by ihsandemir** [comment]
Can you provide the complete code with headers included?

**Comment by gauthamu** [comment]
`#include<iostream>
#include <sstream>
#include"hazelcast/client/HazelcastAll.h"
int main()
{
....
hazelcast::client::IMap<std::string, std::string> m = hz.getMap<std::string, std::string>("map"); hazelcast::client::adaptor::RawPointerMap<std::string, std::string> map(m);
......
}`

**Comment by ihsandemir** [comment]
We do not have the adaptor headers included in HazelcastAll.h . Just add this line for now:

#include "hazelcast/client/adaptor/RawPointerMap.h"
