### ISSUE TITLE
Crash at client start

### ISSUE THREAD

**Issue by wsw2016** [hazelcast/hazelcast-cpp-client#198]
If at the client start   _client = new hazelcast::client::HazelcastClient(clientConfig)_
no Hazelcast server is started, the client crashes.
Issue: during _lifecycleService.shutdown()_ in HazelcastClient.cpp the _nearCacheManager_ is dereferenced in ClientContext.cpp, which will be created after successfull initialisation.

Proposal: shift the line _nearCacheManager = createNearCacheManager()_ before _lifecycleService.start()_ in file HazelcastClient.cpp.

**Comment by ihsandemir** [comment]
Can you try the latest code? this part is changed and should be fixed already.

**Comment by ihsandemir** [comment]
@wsw2016 NearCache implementation is completed now. Can you retry an let us know how it works for you?

**Comment by ihsandemir** [comment]
This is already solved by latest code merges.
