### ISSUE TITLE
Add write/readUTFArray interface to Portable Writer/Reader

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-cpp-client#224]
Portable writer/reader is missing the write and read UTF array which exis at Java API (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/nio/serialization/PortableReader.java#L191 https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/nio/serialization/PortableWriter.java#L208)

**Comment by musaddiqrg** [comment]
This would be quite useful, was there a reason this was never done?

**Comment by ihsandemir** [comment]
@musaddiqrg I don't remember the reason why it can not be done. Especially, with the upcoming 4.0 release, we need to add this. I am reopening the issue.
