### ISSUE TITLE
error of asio while compiling with SSL enable

### ISSUE THREAD

**Issue by ravidhiman** [hazelcast/hazelcast-cpp-client#284]
‘class asio::io_service’ has no member named ‘restart’

**Comment by ihsandemir** [comment]
Hello, 

Can you please write down the commands that you used to compile including the library checkout? 

Please refer to the scripts testLinuxSingleCase.sh and releaseLinux.sh to see how we use the flags and such. It may be a flag or missing checkout problem.

**Comment by ravidhiman** [comment]
cmake .. -DHZ_LIB_TYPE=SHARED -DHZ_BIT=64 -DCMAKE_BUILD_TYPE=Release -DHZ_COMPILE_WITH_SSL=ON -DHZ_USE_C11=ON

Which version of asio did you use?

**Comment by ravidhiman** [comment]
hello.. the above issue of "‘class asio::io_service’ has no member named ‘restart’" is resolved by recursive update.. but when i am trying to link the library (HazelcastClient3.8.2-SNAPSHOT_64) with test program , i am getting lot of SSL linking errors:
Linking CXX executable awsClientWithKey
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `SSL_CTX_free'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `X509_NAME_get_index_by_NID'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `SSLv23_client_method'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `HMAC_Final'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `SSL_CIPHER_get_bits'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `BIO_ctrl'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `TLSv1_1_server_method'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `SSL_get_ex_data_X509_STORE_CTX_idx'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `CRYPTO_set_locking_callback'

**Comment by ihsandemir** [comment]
Since, you use flag: -DHZ_COMPILE_WITH_SSL=ON you enabled TLS feature. TLS enabled library requires that you have openssl installed and you need to link the openssl libs.

**Comment by ravidhiman** [comment]
which version of openssl is required?

**Comment by ihsandemir** [comment]
Please read https://github.com/hazelcast/hazelcast-cpp-client#building-the-project  It requires 1.0.2 version.

**Comment by ravidhiman** [comment]
I installed openssl 1.0.2 version but still facing same problem on ubunutu 14.04
and also why hazelcast library doesnt show depedency of ssl and crypto
ldd libHazelcastClient3.8.2-SNAPSHOT_64.so
        linux-vdso.so.1 =>  (0x00007ffde5998000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd1c92ba000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd1c90a4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd1c8cdf000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd1c9a3b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd1c89d9000)

**Comment by ihsandemir** [comment]
Did you link like this?: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/CMakeLists.txt#L184

Are you pointing the library directory in your compilation? Please shared your compilation line which has all the flags. You should have the openssl lib directory in your link directory list. Dependency will show when you link your executable.

**Comment by ravidhiman** [comment]
cmake .. -DHZ_LIB_TYPE=SHARED -DHZ_BIT=64 -DCMAKE_BUILD_TYPE=Release -DHZ_COMPILE_WITH_SSL=ON
-- Build type is  Release
-- HAZELCAST_GIT_COMMIT_DATE = "2017-05-12"
-- HAZELCAST_GIT_COMMIT_ID = "12447c3"
-- Preparing hazelcast client .....
-- Generating SHARED Library
-- Building the library with SSL support.
-- Linux-3.13.0-107-generic
-- LINUX ENVIRONMENT DETECTED
-- 64 Bit
-- Configuring done
-- Generating done

**Comment by ihsandemir** [comment]
No, nit our library built but I wanted you to shared the compilation and link lines for your own application. If you use cmake for your application, you can do this when you make: make VERBOSE=1 to print the flag details.

**Comment by ravidhiman** [comment]
/usr/bin/cmake -E cmake_link_script CMakeFiles/awsClientWithKey.dir/link.txt --verbose=1
/usr/bin/c++      CMakeFiles/awsClientWithKey.dir/AwsClientWithKey.cpp.o  -o awsClientWithKey -rdynamic -lssl -lcrypto -lHazelcastClient3.8.2-SNAPSHOT_64 -lpthread
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `SSL_CTX_free'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `X509_NAME_get_index_by_NID'
//usr/local/lib/libHazelcastClient3.8.2-SNAPSHOT_64.so: undefined reference to `SSLv23_client_method'

**Comment by ihsandemir** [comment]
Hello @ravidhiman 

Your environment is missing the openssl installation or you did not configure the directory to search for it as our cmake is looking for. 

If you know where your ssl installation is can you please set the following cmake environment when running cmake: -DHZ_OPENSSL_LIB_DIR=.... and -DHZ_OPENSSL_INCLUDE_DIR=...   Also make sure that you remove the build folder and recreate it before re-running the cmake command.

Let me know how it works for you.

**Comment by ihsandemir** [comment]
Hello @ravidhiman We also added support for external boost and asio library usages per this PR: https://github.com/hazelcast/hazelcast-cpp-client/pull/490

I did not hear from you regarding the fixes. Let me know how they work for you. 

I am closing the issue for now. Please feel free to reopen if the problem still persists.
