### ISSUE TITLE
Clarify use of TLS feature in hazelcast-cpp-client

### ISSUE THREAD

**Issue by justinpa-asg** [hazelcast/hazelcast-cpp-client#306]
I'm curious about note in [README.md](https://github.com/hazelcast/hazelcast-cpp-client/commit/0a42ea318d487720c73db42c774cc768819bcb68):

> TLS Feature
>  -Note: This is a Hazelcast IMDG Enterprise feature.

If hazelcast-cpp-client uses Apache 2.0 license, Boost.Asio and OpenSSL both use their own lenient licenses, and this project even provides TLS-enabled [binary artifacts for download](https://github.com/hazelcast/hazelcast-cpp-client/releases#user-content-downloads), how can TLS be a restricted enterprise feature?

**Comment by ihsandemir** [comment]
It is only server side restriction. There is no restriction at the client side. Without the server TLS enabled client can not talk using TLS.
