### ISSUE TITLE
byte array support

### ISSUE THREAD

**Issue by leyryan33** [hazelcast/hazelcast-cpp-client#307]
It looks like in TypeIDS.h there is missing support for:
getHazelcastTypeId(const std::vector<byte> *object)

and also within ObjectDataInput.h there is missing support for:
template<>
void ObjectDataInput::readInternal(int typeId, std::vector<byte> *object)

It looks like all the other functions necessary exist (ObjectDataInput::readByteArray), so I'm curious if this was intentional or not.

**Comment by ihsandemir** [comment]
Hello,

What do you mean by ObjectDataInput::readInternal(int typeId, std::vector *object) ? What is the type of the vector template? Can you please provide a concrete example on what you want to achieve?

There are already the supported vector serialisations like here: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/include/hazelcast/client/serialization/ObjectDataInput.h#L191

And also for toObject method here:
https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/include/hazelcast/client/serialization/pimpl/SerializationService.h#L243

These should normally be OK.

**Comment by leyryan33** [comment]
So if you have a 
TransactionalQueue<std::vector<hazelcast::bytes>> queue
and you do queue.poll();

It calls into this readInternal: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/include/hazelcast/client/serialization/ObjectDataInput.h#L239

Because there does not exist a ObjectDataInput::readInternal(int typeId, std::vector< byte >* object) specialization

It then throws an exception because there is no serializer registered to process.

I also believe there is a compiler error that occurs when you try to compile the same above queue:
queue.poll();

Because it compiles until this line: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/include/hazelcast/client/serialization/ObjectDataInput.h#L207

And TypeIDS.h does not define a getHazelcastTypeId(const std::vector< byte > *object)

Sorry for the confusion, I didn't realize that my above comment dropped the T = byte in my std::vector

**Comment by ihsandemir** [comment]
Ok, i see the problem. Can you try using TransactionalQueue<std::vector<char> > ? This will be pretty much the same.

Meanwhile, I will add 

                template<>
                HAZELCAST_API Data SerializationService::toData<std::vector<byte> >(const std::vector<byte> *object);

specialisation in SerializationService. This should solve the problem.

Thanks for reporting.
