### ISSUE TITLE
DataOutput::writeUTF() writes invaild data 

### ISSUE THREAD

**Issue by mstier** [hazelcast/hazelcast-cpp-client#308]
If the string which is to be written contains UTF8-encoded multibyte characters, the length of the string is wrongly calculated. Due to a bug in DataOutput::getUTF8CharCount(), some characters are skipped and the wrong length is returned. 
I've created a fix and will submit a pull request after initial tests.

**Comment by ihsandemir** [comment]
Hello,

We followed the same calculation as performed at Java side for size calculation: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/ByteArrayObjectDataOutput.java#L253

Check this out. I believe we are not handling UTF characters encoded longer than 3 bytes. But it should work for UTF characters up to 3-bytes. Do you have a test which shows what may be wrong? we can have a better idea if there is a bug there with a test.

I will double check on your PR solution.

Regards,
ihsan

**Comment by mstier** [comment]
Hi!
No, your length calculation in Java is different from the calculation in C++. In Java, you use str.length() to get the number of characters which is valid since Java strings are two-byte-per-character-strings. Conversion to Utf8 happens later at Bits.writeUtf8Char(). In C++ you get an already Utf8-encoded string which contains characters with variable number of bytes. You count the number of characters by analyzing Utf8 code points but in case of a start-byte (0x7f) you always skip two other bytes even if the character has only one additional byte. For a test: just call DataOutput::getUTF8CharCount() with this string: "xyzä123". Length should be 7, the function returns 6. The character 'ä' is "\u00E4"  or Utf-8: 0xC3 0xA4.

Regards,
Markus

**Comment by ihsandemir** [comment]
Hello Markus,

I think you misunderstood the meaning of the length field written before the actual bytes are written. It is NOT the number of bytes but it is the number of UTF-8 characters. You should check the Hazelcast Open Binary Client Protocol (https://hazelcast.org/documentation/#open-binary) section Client Protocol Data Types. It states:

```
String encoded as a byte array with UTF-8 encoding. Initial 4 bytes (uint32 type) represents the number of UTF-8 characters in the the string.
Example: the string “bad” {0x62,0x61,0x64} will be encoded as 0x03,0x00,0x00,0x00,0x62,0x61,0x64. Only UTF-8 code points 0x0000 up to 0xFFFF (3-bytes) are supported.
```

Hence, the implementation conforms to this statement. Hence, the result for your example string is expected to be 6 according to the protocol.

**Comment by mstier** [comment]
Hello Ihsan,

sorry for being obstinate but I believe you're wrong. I know that the protocol denotes the number of characters not the number of bytes. But the string "xyzä123" from my example above consists of 7 characters using 8 bytes: 0x78 0x79 0x7A 0xC3 0xA4 0x31 0x32 0x33. 
Once more: DataOutput::getUTF8CharCount() has a bug in counting the _characters_ when the string contains two-byte UTF-8 characters like 'ä'.

Regards,
Markus

**Comment by ihsandemir** [comment]
Hello Markus,

My bad. Yes, you are correct. I like the fix that you submitted. I formed a PR to fix it and wrote a test to verify it here: https://github.com/hazelcast/hazelcast-cpp-client/pull/311

Thanks for reporting this. It was a good catch.

Regards,
ihsan
