### ISSUE TITLE
Hazelcast native client thread hangs while trying to obtain a connection.

### ISSUE THREAD

**Issue by KalebNeguisse** [hazelcast/hazelcast-cpp-client#317]
I'm trying to use Hazelcast native c++ client on Windows(MFC). I try to get a connection and the thread hangs I have been able to trace it to ClusterService.cpp

    bool ClusterService::start() {
                ClientConfig &config = clientContext.getClientConfig();
                std::set<MembershipListener *> const &membershipListeners = config.getMembershipListeners();
                listeners.insert(membershipListeners.begin(), membershipListeners.end());
                std::set<InitialMembershipListener *> const &initialMembershipListeners = config.getInitialMembershipListeners();
                initialListeners.insert(initialMembershipListeners.begin(), initialMembershipListeners.end());

                util::Thread *t = new util::Thread("hz.clusterListenerThread",
                                                   connection::ClusterListenerThread::staticRun, &clusterThread);
                clusterThread.setThread(t);
clusterThread.startLatch.await();

It never returns from the last line in the above code (clusterThread.startLatch.await()). 
Can somebody please help?

**Comment by ihsandemir** [comment]
Can you write your client version and attach the logs at the client and server side?

**Comment by KalebNeguisse** [comment]
The client version is 3.8.1 but I also tried it with 3.8.2. There is no server side log because I'm testing and writing logic to handle the case where there is no server running. I want the connection to try and connect and throw hazelcast::client::exception::IllegalStateException. Since this is a GUI native application is there a way to redirect logging to a file for c++ client?

**Comment by KalebNeguisse** [comment]
Upon further investigation I was able to see that it gets stuck in this function bool CountDownLatch::awaitMillis, which in turn calls 	void sleepmillis in src\hazelcast\util\Util.cpp. I see it looping on Sleep indefinitely which is set as HZ_INFINITE.

**Comment by KalebNeguisse** [comment]
The following picture shows that my MFC application starts 4 hazelcast threads by for some reason the countDownLactch never seems to go to 0 when there is no clusterService. 

![image](https://user-images.githubusercontent.com/20207551/28577588-2a2e36ba-7125-11e7-8c97-c76a42063f41.png)

**Comment by ihsandemir** [comment]
Hello @KalebNeguisse We already have a passing test case at https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/test/src/cluster/ClusterTest.cpp#L310 for what you are describing. Is this your case?

If not, can you provide a reproducer test case so that I can test for it?

**Comment by KalebNeguisse** [comment]
Can we do a video call and share my screen so I can show you? As I cannot provide you with a test case because the code I'm testing is part of a bigger code base that I cannot share.

**Comment by KalebNeguisse** [comment]
I also see this.

Jul 25, 2017 12:57:18 PM SEVERE: [HazelcastCppClientNOT_FOUND] [ViewDirect for Networks] [11816] Error while connecting to cluster! =>ExceptionMessage {Unable to connect to any address in the config! =>ExceptionMessage {Send failed. A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
} at TcpSocket::send} at ClusterService. 


Normally when I can't connect to the node I see 

Jul 25, 2017 01:00:29 PM SEVERE: [HazelcastCppClientNOT_FOUND] [vdrnetsharedcfg] [17336] Error while connecting to cluster! =>ExceptionMessage {Unable to connect to any address in the config! =>ExceptionMessage {Failed to connect to 127.0.0.1:5706 in 5 milliseconds} at TcpSocket::connect } at ClusterService

**Comment by KalebNeguisse** [comment]
Ok here. I think you can use this to investigate. I'm using a static initialization, and I get. I expect to get not allowed to connect
 
Jul 25, 2017 01:00:29 PM SEVERE: [HazelcastCppClientNOT_FOUND] [vdrnetsharedcfg] [17336] Error while connecting to cluster! =>ExceptionMessage {Unable to connect to any address in the config! =>ExceptionMessage {Failed to connect to 127
[testHazelcast.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/1174557/testHazelcast.zip)
.0.0.1:5706 in 5 milliseconds} at TcpSocket::connect } at ClusterService

**Comment by KalebNeguisse** [comment]
Ok Here I finally got an executable you can use to reproduce the problem. Just run test.exe, you will see hazelcast hanging

[testHazelcast.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/1175010/testHazelcast.zip)

**Comment by ihsandemir** [comment]
I can not really debug or change the code and recompile with your project but I did try it locally on my setup and it actually works. You may be trying to use an unconnected client. We need to see the logs for sure.

You did set the log level too high which is why you see no logs. Logs are printed at the stdout. We need the logs. Do not set any log level, default value of INFO should be sufficient. 

Why are you using dummy client? You are setting clientConfig.setSmart(false);  You do not normally need this unless you want to work with a dedicated server only in the cluster and no connection to other servers. It will decrease performance.

The logs are printed to stdout. Can you please not set the log level to SEVERE and send me the output of your test run? Can you please put print statements inside catch clause and the happy path as well as inside VdrHazelcastWrapper::isHazelcastClientConnected. This way we can track the progress for each step. Let's look at this.

**Comment by KalebNeguisse** [comment]
Thanks for the reply. Are you saying the last zip file I sent you worked for you? I sent you two of them, the first one would work. But the second one is different and that one hangs. I can prints but the problem is it never comes back from HazelcastClient hazelcastClient(clientConfig); If you follow the hazelcast code there is a latch.await that just waits forever. The last zip file I sent you demonstrates this, I tired on many machines. Please run test.exe from the last zip I sent, there should be an exe and a DLL called LIBRA in it. The executable is testHazelcast\TEST\x64\Debug. I am away from the office today, but I will try the logging level first thing tomorrow morning. Thank you for the fast reply.

**Comment by ihsandemir** [comment]
I downloaded the second one which is 19 MBs(19217061 bytes). 

When I try this code that you sent and I see it waits and if stop at the debugger I see that your main thread is at VdrHazelcastWrapper::getSize call. Your code waits there but it may be some other problem such as trying to use an already shutdown client, or an invalid pointer, or some other problem. That is why we need to see the logs. Put print logs before and after each call and lets see what is written as well. The client logs will tell you exactly what it is doing and if it is shutdown or not. Your code also allocates the client at the stack (pointer line is commented out). 

What is working is: I just do instantiate a client as a dummy client like you do with no cluster and here is a test I just put together for your case: https://github.com/hazelcast/hazelcast-cpp-client/pull/318 

Waiting your log output.

**Comment by KalebNeguisse** [comment]
Ok I put print statements  and I set the logging level to normal. I have attached the latest code. 
[testHazelcast.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/1179769/testHazelcast.zip)

I added a print statement before and after the call to HazelcastClient hazelcastClient(clientConfig); and anything after is not executed. I now see logging from Hazelcast and I see the following

Jul 27, 2017 07:35:10 AM INFO: [HazelcastCppClientNOT_FOUND] [ViewDirect for Networks] [20816] (HAZELCAST_GIT_COMMIT_DATE:HAZELCAST_GIT_COMMIT_ID) LifecycleService::LifecycleEvent STARTING

And it never seems to come back from this. The following is all the code I see in the console with the new modified code with print statements.

Adding address 127.0.0.1
Set Attemp period.
Set Group name and password.
Set Group
Before executing code  HazelcastClient hazelcastClient(clientConfig);
Jul 27, 2017 07:35:10 AM INFO: [HazelcastCppClientNOT_FOUND] [ViewDirect for Networks] [20816] (HAZELCAST_GIT_COMMIT_DATE:HAZELCAST_GIT_COMMIT_ID) LifecycleService::LifecycleEvent STARTING

**Comment by KalebNeguisse** [comment]
I believe if you were to perform the following you would be able to reproduce. What you need is hazelcast.dll (Your library), a wrapper library for hazel cast (wrapper.dll). an dll that calls the wrapper (initialize wrapper object at load time, which must call HazelcastClient hazelcastClient(clientConfig);. Basically static initializers) and an excutable that calls the top level dll;

executable-->Library.dll(static initializer with warpper object)-->haelcastwrapper.dll-->hazelcast.dll

**Comment by ihsandemir** [comment]
@KalebNeguisse Can you please attach the full logs?

**Comment by KalebNeguisse** [comment]
Ok done. Here is the latest code.
[testHazelcast.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/1180109/testHazelcast.zip)

The only log i see is the following

Adding address 127.0.0.1
Set Attemp period.
Set Group name and password.
Set Group
Before executing code  HazelcastClient hazelcastClient(clientConfig);
Jul 27, 2017 09:42:36 AM INFO: [HazelcastCppClient3.8.2] [ViewDirect for Networks] [2284] (NOT_FOUND:NOT_FOUND) LifecycleService::LifecycleEvent STARTING

![image](https://user-images.githubusercontent.com/20207551/28673208-fc57704e-72af-11e7-8719-a119bd22881e.png)

**Comment by KalebNeguisse** [comment]
Hi,

In this latest zip I created all the things you would need to debug i added the wrapper project as well. So all the logs that you asked me to add is now accessible and compile-able to you too. The zip file came to about 30 MB and it won't let me attach is there another way to send it to you? This zip file contains the entire thing you need, please let me know if you want it.

Thank you

**Comment by KalebNeguisse** [comment]
@ihsandemir . Hi is there any update? Anything I can provide?

**Comment by ihsandemir** [comment]
@KalebNeguisse Yes, can you upload via google drive or similar and send me the link? It will help a lot.

**Comment by KalebNeguisse** [comment]
Here is the link for the zip file 
https://drive.google.com/file/d/0B1FmxF4Vnb9UTHFfMXFvT1NtcVU/view?usp=sharing

No there is no process waiting on port 127.0.0.1:5701. The above link contains the entire executable.

**Comment by KalebNeguisse** [comment]
@ihsandemir . Hi is there any update? Anything I can provide?

**Comment by ihsandemir** [comment]
@KalebNeguisse I will look at it today.

**Comment by KalebNeguisse** [comment]
@ihsandemir Good afternoon. Any updates on this? Anything I can help with or provide you?

**Comment by ihsandemir** [comment]
@KalebNeguisse It seems that you may have mixed the 3.8.1 library with 3.8.2 library. When I run the project, I see a log indicating that the client version is 3.8.2 but then I actually observe that you have 3.8.1 dlls in the project folders and when I debug, I observe that it stops at 3.8.1 dll. There seems to be a major problem with using the correct library at build and runtime. Can you simplify your solution to a single project with no LIBRA.dll but just put everything into TEST project and your executable only depends on Hazelcast 3.8.2 dll. I think we can further simplify the case this way. It is highly possible that you compile with one library use another one during runtime and this will cause undefined behaviours.

**Comment by KalebNeguisse** [comment]
@ihsandemir No I do not have a mix. I started with 3.8.1, and then I wanted to test with 3.8.2. But i didn't want to  change my build files or anything else. So i renamed the 3.8.2 dll to 3.8.1. That dll you see as 3.8.1 is in fact 3.8.2. There is no major problem in build as I explained I renamed the dll to 3.8.1 because I originally started with 3.8.1. This is not a compilation or library problem. I have debugged into your code. The problem you can reproduce as well, if you were to try to get a hazel connection in a static initializers.    You need LIBRA because the code to get a hazelcast connection is invoked when the library is loaded.

**Comment by KalebNeguisse** [comment]
@ihsandemir This is the only way I know to reproduce the problem and the way I am using it. I cleaned the code to make use and build with 3.8.2. Everyting you need to debug is in this application. Please I really need a resolution on this. Here is the new link https://drive.google.com/file/d/0B1FmxF4Vnb9UWW9iNTMzYVVBT3M/view?usp=sharing

**Comment by KalebNeguisse** [comment]
@ihsandemir Good afternoon. Any updates on this?

**Comment by ihsandemir** [comment]
Hello @KalebNeguisse 
Sorry I could not reply earlier. I tried your new project. I think you still have problem with using up to date dll's in your project. Try this: clean your project. Then search for .dll and .lib files and you will see that you have vdrHazelcast.lib and other libs still remain. Please find attached https://drive.google.com/file/d/0B465urP0EmqMN2ZLSlJiU25mTFU/view?usp=sharing is the project where I removed all the libraries except Hazelcast 3.8.2 dll. And you can see that the project does not build. I expect that your project dependencies to be set up correctly and when cleaned the project I should only see Hazelcast external lib in the folders. You have a problem setting dependencies between projects in your solution.

**Comment by KalebNeguisse** [comment]
Hello @ihsandemir
Please feel free to delete the libraries that you think is not valid. When you rebuild everything you will get new ones, the extra one I kept because I wanted a back just in case. Please I have to strongly urge you to stop thinking it is a library outdated problem. I traced to your code and I see it stuck in an endless loop because the thread is not coming back. This little app I gave you reproduces the problem. I am 100% sure it has nothing to do with loading libraries or old libraries. Why don't you just debug it and trace all the way to your code and you will see it. I have built, rebuilt and linked and tried everything and it is not a library problem. I what took what you sent me and tried to compile and it did have an error, but I noticed that you were pointing to the wrong location, so I changed Additional Library Directories to C:\VC++\testHazelcast\TEST\x64\Debug;%(AdditionalLibraryDirectories), relative path for you would be testHazelcast\TEST\x64\Debug and then it  works fine. Please I urge to stop focusing on library loading otherwise we will not get anywhere. Change the path to the path I mentioned and you will be able to build. Then you can reproduce and debug the problem. 

![image](https://user-images.githubusercontent.com/20207551/29229497-c14effae-7eac-11e7-853a-e2afb7f82efc.png)

**Comment by ihsandemir** [comment]
Hello @KalebNeguisse 
I debugged into the application. Here is my finding:

The library needs to create threads during startup. It executes this line: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/src/hazelcast/util/Thread.cpp#L253  And the started thread should run executing this method: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/src/hazelcast/util/Thread.cpp#L230

I put debug statements and saw that the first line in thread execution method (controlledThread) is never run (no print and it does not also stop at a breakpoint inserted at the entry). Hence, there seems to be a problem for the library not being able to run threads(can create but thread does not run). This seems to be specific to your setup. It may be related to some security settings or some other permissions which I did not understand yet. Furthermore, when you pause while it waits indefinitely you can also see that all the created threads, there is no stack calls, they are somehow prevented from execution which I did not understand yet the reason. Since, no thread can be started, the library can not initialise and the cluster service waits since it assumes that the created thread would run but it did not execute the entry method at all. Need to figure out why the thread does not work. I see that the CreateThread returns a valid non-NULL thread id, and hence I assume that it is success but it does not run the entry point of the thread method. I have a library with debug symbols and debug logs put at the entry points of the mentioned library methods and I can share it if you want to try yourself.

**Comment by KalebNeguisse** [comment]
Hello @ihsandemir

Hi Thank you for getting back to me. Yes You can share what you have, but I too have seen everything you have mentioned (except I did not know exactly the sequence of events once it gets to Hazelcast code). However I fail to see how this can be a security issue on my end if it behaves the same on your machine. As you can see, my code only invokes a wrapper around your clients connection object at library load time. I will be happy to help in anyway I can but I do not know the internals of hazelcast client to be as efficient and methodical as you. Let me know if you need anything else from me.

**Comment by ihsandemir** [comment]
@KalebNeguisse Here are more findings:

The project works if you do not start the client by defining a static variable in entry.cpp. Please see attached project (change paths to relative paths if not compiles): https://drive.google.com/file/d/0B465urP0EmqMMDB5dFZpRTlzejA/view?usp=sharing

So, the problem is kind of isolated to using the static variable in entry.cpp. 

static VdrHazelcastWrapper test;

**Comment by KalebNeguisse** [comment]
Hello @ihsandemir

Yes I agree the static variable is when this problem manifests itself. Are you telling me that Hazecast cannot be invoked from a static variable?

**Comment by ihsandemir** [comment]
@KalebNeguisse No, there is probably some other problem when using static variable that way, it may be a dll specific problem (just don't now), because the threads are not starting that way. Did you try also static method instead of static variable?

**Comment by KalebNeguisse** [comment]
Hello @ihsandemir

I haven't tried that. Did you try it?

**Comment by KalebNeguisse** [comment]
Hello @ihsandemir

Can you please provide me with updates?

Thank you

**Comment by KalebNeguisse** [comment]
Hello @ihsandemir

Can you please provide me with updates?

Thank you

**Comment by KalebNeguisse** [comment]
Hello @ihsandemir

Can you please provide me with updates?

Thank you

**Comment by KalebNeguisse** [comment]
Is there anybody that can help me with this?

**Comment by KalebNeguisse** [comment]
Hello @ihsandemir 
Do you have any updates on this for me?

**Comment by ihsandemir** [comment]
Hello @KalebNeguisse We made significant changes in connection mechanism which will be released at 3.10. Can you please retry with this latest release and let me know if the problem still persists? I believe the fix https://github.com/hazelcast/hazelcast-cpp-client/pull/392 most probably will solve your problem.

**Comment by KalebNeguisse** [comment]
@ihsandemir  Hello, is 3.10 released or is it going to be releases soon?

**Comment by KalebNeguisse** [comment]
@ihsandemir Hello, is 3.10 released or is it going to be releases soon?

**Comment by ihsandemir** [comment]
3.10 will be released in a few days. Keep an eye.

**Comment by ihsandemir** [comment]
Closing this issue since I did not get any feedback from the user if the related PR fixed the problem or not and I can not generate the problem. Please feel free to reopen if the problem is not fixed.
