### ISSUE TITLE
cpp client fails to connect to remote instance

### ISSUE THREAD

**Issue by aparnam-asg** [hazelcast/hazelcast-cpp-client#326]
I am trying to run a small client on Linux that connects to Hazelcast instance running on remote Windows machine. But it fails during creation of HazelcastClient. If I start Hazelcast instance locally on the same machine, this client program is working fine. 

I see logs on both server side and client side. It seems to reach the server and make connection. But it gets some kind of error on the client. If I use Java client, it connects fine. Below is the client log

Aug 02, 2017 03:08:48 PM INFO: [HazelcastCppClient3.8.1] [dev] [140645758248736] (20170503:6f5da07) LifecycleService::LifecycleEvent STARTING
Aug 02, 2017 03:08:48 PM FINEST: [HazelcastCppClient3.8.1] [dev] [140645726762752]  Trying to connect to owner node 0. attempt
Aug 02, 2017 03:08:48 PM INFO: [HazelcastCppClient3.8.1] [dev] [140645726762752] Connected and authenticated by Address[10.0.75.1:6701]. Connection id:1 , socket id:8 as owner connection. Client uuid: d145b934-eb74-4f48-8644-e4f1c24ec550. Owner member uuid: 49d93cd7-f620-4215-a341-db51e9143110
Aug 02, 2017 03:08:48 PM INFO: [HazelcastCppClient3.8.1] [dev] [140645726762752] LifecycleService::LifecycleEvent CLIENT_CONNECTED
Aug 02, 2017 03:08:48 PM INFO: [HazelcastCppClient3.8.1] [dev] [140645726762752]
Members [1]  {
        Member[10.0.75.1]:6701 - 49d93cd7-f620-4215-a341-db51e9143110
}

terminate called after throwing an instance of 'hazelcast::client::exception::IException'
  what():  ExceptionMessage {No member in member list!!} at const Member& RoundRobinLB::next()
Aborted (core dumped)

**Comment by ihsandemir** [comment]
@aparnam-asg  Can you attach the stack trace of the core dump?

**Comment by aparnam-asg** [comment]
[HazelTestFiles.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/1197430/HazelTestFiles.zip)

**Comment by aparnam-asg** [comment]
I just want to know why it gets an exception. In the sample code I am not handling exceptions, true. In real application code, we do handle exception but I am expecting it to connect and not throw exception.  If there is something wrong in configuration or something else I am missing?

**Comment by ihsandemir** [comment]
Thanks @aparnam-asg We normally should not see this exception on client start. I will examine deeply, i will probably try your configuration where the server is at windows and client is at Linux. I will update you later with my findings.

**Comment by aparnam-asg** [comment]
Thank you @ihsandemir . I will look forward for your update.  I actually tried Windows to Windows, Windows to Linux, Linux to Windows. All combinations failed for native client. If I run server on same machine it works. As Java client works as expected with remote server,  I was thinking my configuration is okay. Thanks again for your time on this.

**Comment by ihsandemir** [comment]
Hello @aparnam-asg ,

I believe your problem may be the private public ip problem. From the logs at the server side, it says this:

INFO: [10.0.75.1]:6701 [dev] [3.8.3] Connection[id=1, /10.10.6.171:6701->/10.10.4.31:46887

It means that the server ip is 10.10.6.171 but if you look at the member list above you see this:

Member [10.0.75.1]:6701 - 3fb8b01f-d1f1-4e3a-b02d-80c649dff5a3 this

The client uses the member list retrieved which is [10.0.75.1]:6701 to connect and send further requests. But I believe you may not have access to [10.0.75.1]:6701 from the client machine. You can confirm it by just doing this: telnet 10.0.75.1 6701 from the client machine and see if any connection. The ip 10.10.6.171 seems to work but  10.0.75.1 does not.

Please check this: http://docs.hazelcast.org/docs/3.8.3/manual/html-single/index.html#public-address
You can configure the server public ip address and it will most probably help. Let me know if this was your problem connecting.

**Comment by aparnam-asg** [comment]
Awesome. It worked. Thanks a lot.
