### ISSUE TITLE
Inefficient ObjectDataInput::readByteArray() 

### ISSUE THREAD

**Issue by RomanB0** [hazelcast/hazelcast-cpp-client#328]
Hi,

I'm using custom IdentifiedDataSerializable class with simple integer and byte array fields.
Using profiling tools (callgrind) I found that the **ObjectDataInput::readByteArray()** is very inefficient causing huge CPU load of the whole binary. 

The problem is, that readArray()  [hazelcast/include/hazelcast/client/serialization/pimpl/DataInput.h] does read data one by one in a loop, while for each byte it calls readByte() [hazelcast/src/hazelcast/client/serialization/pimpl/DataInput.cpp] which does moreover an extra buffer size check checkAvailable(), although this check was already done at the beginning of readArray().

Problem is present in 3.8.3 version and older.

**Workaround**
It is possible to replace readByteArray() with a sequence of readInt() to get the byte array length and then readFully() to populate the prearranged buffer with the given size.

Thank you,
Roman

**Comment by ihsandemir** [comment]
Yes, I think we can change this for all primitive array reads. Thanks for reporting.

**Comment by RomanB0** [comment]
Thank you very much, that would be great! 

I found also one more place, which seems to consume too much CPU and might be worth reviewing.
The ResponseParameters() which was called roughly x100.000 times, calls the ClientMessage::get(<Data>) several billion times x1.000.000.000 and takes 10% CPU in my test case.

hazelcast::client::protocol::codec::MapGetCodec::ResponseParameters::ResponseParameters(hazelcast::client::protocol::ClientMessage&)

hazelcast::client::serialization::pimpl::Data hazelcast::client::protocol::ClientMessage::get<hazelcast::client::serialization::pimpl::Data>() 

Thank you.
