### ISSUE TITLE
Unable to specify include and lib dirs for OpenSSL on Windows and on Linux

### ISSUE THREAD

**Issue by justinpa-asg** [hazelcast/hazelcast-cpp-client#330]
There are bugs in CMakeLists.txt. Please fix, e.g.

```
$ git diff CMakeLists.txt
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b6fd4ee9..312ac8bc 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -200,11 +200,11 @@ IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MP /EHsc /bigobj ${HZ_C11_FLAGS}")

        if (${HZ_COMPILE_WITH_SSL} MATCHES "ON")
-               if ("x${HZ_OPENSSL_INCLUDE_DIR}" MATCHES "x")
+               if ("x${HZ_OPENSSL_INCLUDE_DIR}" STREQUAL "x")
                        set (HZ_OPENSSL_INCLUDE_DIR C:\\OpenSSL-Win64\\include)
                endif()

-               if ("x${HZ_OPENSSL_LIB_DIR}" MATCHES "x")
+               if ("x${HZ_OPENSSL_LIB_DIR}" STREQUAL "x")
```

The HZ_COMPILE_WITH_SSL section is missing for Linux. I copied 18 lines for Darwin and pasted for Linux. How do we eliminate in link:
```
-Wl,-rpath,${HZ_OPENSSL_LIB_DIR}
```

README.md is missing dashes:
> You can provide your openssl installation directory to cmake using the following flags:
> > DHZ_OPENSSL_INCLUDE_DIR="Path to open installation include directory"
> > DHZ_OPENSSL_LIB_DIR="Path to openssl lib directory"

**Comment by ihsandemir** [comment]
Hello @justinpa-asg 

The reason that I did not add directory for Linux was because it always installed it in the same system library folder and the build finds it. Which environment did you try in? How did you install openssl? If you used a custom folder for openssl, that may be the reason for such a need. I can add it if we really need it but initially it was not put to Linux intentionally since the openssl related include and libs were already in the path we already use for build.

**Comment by justinpa-asg** [comment]
Hi @ihsandemir 

Our team builds our own version of OpenSSL with FIPS support. Thus we want to specify an alternative location for it. Copying the 18 lines from Darwin section to Linux section allowed me to use the flags. Why have the flags if they can't be used?

**Comment by ihsandemir** [comment]
ok, i see your need. I will add this to Linux section as suggested.

**Comment by justinpa-asg** [comment]
Pull 334 did not resolve any of the problems reported in this issue. For Linux, I get:
```
-- Using HZ_OPENSSL_LIB_DIR: /builds/openssl-1.0.2n/lib
-- Using HZ_OPENSSL_INCLUDE_DIR: /builds/openssl-1.0.2n/include
```
But then:
```
$ ldd libHazelcastClient3.9.1_64.so
        linux-vdso.so.1 =>  (0x00007fffc23ff000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f2e3af3f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f2e3acba000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2e3aaa4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f2e3a710000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003522400000)
```
There's no libssl.so or libcrypto.so linked. I see -isystem /builds/openssl-1.0.2n/include but I do not see -lssl or -lcrypto.
Regarding Windows, MATCHES was not replaced with STREQUAL.

**Comment by justinpa-asg** [comment]
I found [cmake documentation](https://cmake.org/cmake/help/v3.3/command/link_libraries.html) that states: "Specify libraries.. when linking any targets created... below by... add_library()". So link_libraries must precede add_library in CMakeLists.txt. I attached a patch for issue [330](https://github.com/hazelcast/hazelcast-cpp-client/issues/330) and [374](https://github.com/hazelcast/hazelcast-cpp-client/issues/334).

[issue330.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/1704427/issue330.txt)

**Comment by justinpa-asg** [comment]
@ihsandemir When will patches be applied? We must continue to create our own patches for new releases.
