### ISSUE TITLE
specifying a log file for C++ client

### ISSUE THREAD

**Issue by aparnam-asg** [hazelcast/hazelcast-cpp-client#331]
This is more of a question actually. It doesn't look like we can specify a log file to write to in the native client. Console is the only option. However we have a console application which uses this client. And we really don't want to show hazelcast specific output to the user but just send it elsewhere even when it is error level logging.  I wanted to make sure I am not missing something basic, if that is already possible somehow. 
Thanks for your support and time in answering our questions while we are adding these new hazelcast based feature to our product.

**Comment by ihsandemir** [comment]
Hello @aparnam-asg 

Yes, the C++ client logs to the stdout only. Do you have any filtering support in your console application stdout, if yes, may be you can try filtering based on our log format which is standard format for all logs (except member list printing).

I will check if such a support may be added with the product management.

Thanks.

**Comment by KalebNeguisse** [comment]
Hello,

I too have hit this issue, where native code error messages are going directly to the console. Do we have an ETA on when this will be resolved?

Thank you

Kaleb

**Comment by KalebNeguisse** [comment]
IS there any change on this ticket? Please let me know.
