### ISSUE TITLE
Build lib in a context of bigger project

### ISSUE THREAD

**Issue by wsw2016** [hazelcast/hazelcast-cpp-client#332]
If the cpp-client is integrated into a bigger project by
add_subdirectory(hazelcast-cpp-client)
the build fails as the compiler can not find *.h files.

Please replace CMAKE_SOURCE_DIR by PROJECT_SOURCE_DIR in lines 86 and 87 of the
hazelcast-cpp-client/CMakeLists.txt.

It solves the problem.

**Comment by ihsandemir** [comment]
Yes, that sounds good. Thanks for reporting.
