### ISSUE TITLE
problems with posix/GNU API to strerror_r

### ISSUE THREAD

**Issue by wsw2016** [hazelcast/hazelcast-cpp-client#335]
I got following error during compiling on alpine linux v3.5 (for use in docker)
hazelcast-cpp-client/external/include/asio/asio/include/asio/impl/error_code.ipp:110:22: error: could not convert 'strerror_r(value, ((char*)(& buf)), sizeof (buf))' from 'int' to 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}'
     return strerror_r(value, buf, sizeof(buf));

The issue is corrected in official boost
https://github.com/chriskohlhoff/asio/commit/443bc17d13eb5e37de780ea6e23157493cf7b3b9
after some discussions
https://github.com/chriskohlhoff/asio/issues/94

A similar problem was in 
hazelcast-cpp-client/hazelcast/src/hazelcast/util/Util.cpp:137:44: error: invalid conversion from 'int' to 'char*' [-fpermissive]
                 char *errStr = ::strerror_r(errnum, strerrbuf + numChars, buflen - numChars);

I applied similar solution with static functions - see attachment.
[util_cpp.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/1400089/util_cpp.txt)

Afterwards the client compiles well, but I have not run the tests.

**Comment by ihsandemir** [comment]
Can you share the docker image if not private so that I can test it as well?

**Comment by wsw2016** [comment]
Here is the Dockerfile and docker-compose-test.yml files with a short description, how to run the compiling and tests.

[testhz.zip](https://github.com/hazelcast/hazelcast-cpp-client/files/1405273/testhz.zip)

**Comment by ihsandemir** [comment]
@wsw2016 
I tried your docker image. I got the following error: make[2]: *** [CMakeFiles/HazelcastClient3.9.1-SNAPSHOT_64.dir/build.make:855: CMakeFiles/HazelcastClient3.9.1-SNAPSHOT_64.dir/hazelcast/src/hazelcast/client/aws/impl/DescribeInstances.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/normaluser/hazelcast-cpp-client/hazelcast/include/hazelcast/client/internal/socket/TcpSocket.h:46:0,
                 from /home/normaluser/hazelcast-cpp-client/hazelcast/src/hazelcast/client/connection/Connection.cpp:33:
/usr/include/sys/errno.h:1:2: error: #warning redirecting incorrect #include <sys/errno.h> to <errno.h> [-Werror=cpp]
 #warning redirecting incorrect #include <sys/errno.h> to <errno.h>
  ^~~~~~~
cc1plus: all warnings being treated as errors


It found this: https://github.com/armon/bloomd/issues/40

It seems as if we need special porting for alpine linux (e.g. not including sys/errno.h), is that correct? 

Furthermore, our library is compiled with c++98 to be compatible with older compiler versions. Hence, we do not normally test with -std=c++11 flag. Hence, it is better not use this flag.

**Comment by ihsandemir** [comment]
We switched to C++11, and use official boost library as dependency, hence closing this issue.
