### ISSUE TITLE
SSL FIPS compliance: AWS auto discovery, context: asio.ssl error

### ISSUE THREAD

**Issue by aparnam-asg** [hazelcast/hazelcast-cpp-client#337]
Hi,

 We have java application that uses JNI. This JNI code talks to Hazelcast using C++ client. On Amazon, we are using auto discovery using tag name/value. First time application seems to connect fine. But after that, I get the following error:
Error while connecting to cluster! =>context: asio.ssl error

I don't see anything else. Once the application fails, it never reconnects again. It seems like it works first time and that is it. Any idea on why this error happens and if there is anything else I can do to get more details on why ssl works once but fails after?

Thanks for your time

**Comment by aparnam-asg** [comment]
This application is not reusing connection. It shuts down the hazelcast client after use till next request comes in, at which point it starts a fresh client.

**Comment by aparnam-asg** [comment]
Will you be able to provide any insights on how to resolve this type of issue? I tried to reproduce this with just the relevant code in a smaller application but that one works in the exact same environment. I seem to have this issue only when the exact same code is run inside our product. If there is anyway to produce more logs on asio:ssl error, that should help immensely. Thanks for your help

**Comment by ihsandemir** [comment]
Hello,

Are you sure that there is no other log information on the error. Yes, we use boost::asio library to connect https for discovering the AWS member information. I checked at the AWSClient code and here is the place where we throw and IOException: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/src/hazelcast/util/SyncHttpClient.cpp#L100  Can you look again to see if you observe this exception line (assuming that you catch and log this exception)?

A reproducer code would help a lot.

**Comment by aparnam-asg** [comment]
Thanks. Yes, there is nothing else in logs. I catch IException and log it. That just says "HazelcastClient could not be started!". I turned FINEST log level. And on console I see the other log that I mentioned before "Error while connecting to cluster! =>context: asio.ssl error". 

I know, at the minimum I need to provide reproducer code. Funny thing is when I try to extract out the code to a test program, that works, so as of now I can't reproduce it outside of our product. But I did have some progress. There is some other code in that execution path which sends ssl request to another server. And after that hazelcast stuff stops working. Somehow this other request seems to mess up AWS communication after. We enable fips in open ssl in our code. I am not sure if that is any issue. I am trying few more experiments on my end.

**Comment by ihsandemir** [comment]
"We enable fips in open ssl in our code" --> Can you explain how this is done? What kind of ssl code do you use? I wonder if you are setting some ssl options which messes up our requests. Can you try disabling your fips and ssl and try running the product to see if that is causing the problem? If we can isolate it this way, then we can examine how you use ssl in your product and try to understand how it may affect our ssl call to AWS.

**Comment by aparnam-asg** [comment]
We currently build openssl 1.0.2h with fips but plan to upgrade to 1.0.2l. Building with fips is explained in their guide:
https://www.openssl.org/docs/fips/UserGuide-2.0.pdf 

And we turn on fips in our code by calling the following method call:
**FIPS_mode_set(1)**
https://wiki.openssl.org/index.php/FIPS_mode_set()

However, my experiment revealed that during my test fips mode was not yet on. It is turned on in a functionality that was not triggered from my test path. But it did reveal that if ever it gets turned on, auto discovery fails. I get the following error during auto discovery with fips:
_sha256.c(34): OpenSSL internal error, assertion failed: Low level API call to digest SHA256 forbidden in FIPS mode!_

So maybe that is another ticket. And this is easily reproducible. I asked folks internally who are more familiar with openssl/fips. And they say we need it for compliance. And if hazelcast native client is using some unapproved digests, that could be a problem. If you can suggest some alternative that will help though I feel this is a new issue and is unrelated to what I started with. And I am continuing to investigate the original. 

Thanks again for your continued support. We all appreciate it.

**Comment by aparnam-asg** [comment]
I isolated fips issue to EC2RequestSigner::getCanonicalizedRequest which fails trying to get Sha256 hash. Error is from OpenSsl as I have reported before:

sha256.c(34): OpenSSL internal error, assertion failed: Low level API call to digest SHA256 forbidden in FIPS mode!

When I google this, it looks like in fips mode one is expected to use EVP based methods and not low level APIs:
http://openssl.6102.n7.nabble.com/APIs-forbidden-in-FIPS-mode-td44106.html
http://openssl.6102.n7.nabble.com/Low-Level-Digest-if-Fips-mode-td54983.html

Attaching a test program that shows the failure when fips is on.

[HazelFipsTest.cpp.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/1435093/HazelFipsTest.cpp.txt)

**Comment by aparnam-asg** [comment]
For our product purposes, I patched EC2RequestSigner::sha256Hashhex as shown below and I verified it works. 

                std::string EC2RequestSigner::sha256Hashhex(const std::string &in) const {
                    #ifdef HZ_BUILD_WITH_SSL
                    int hashLen = EVP_MD_size(EVP_sha256());
                    unsigned char hash[hashLen];
                    EVP_MD_CTX ctx;
                    EVP_MD_CTX_init(&ctx);
                    EVP_DigestInit_ex(&ctx, EVP_sha256(), NULL);
                    EVP_DigestUpdate(&ctx, in.c_str(), in.size());
                    EVP_DigestFinal(&ctx, hash, NULL);
                    EVP_MD_CTX_cleanup(&ctx);
                    return convertToHexString(hash, hashLen);
                    #else
                    util::Preconditions::checkSSL("EC2RequestSigner::hmacSHA256Bytes");
                    return "";
                    #endif
                }

**Comment by ihsandemir** [comment]
@justinpa-asg 
Hello, sorry for the late response since I was away for vacation. I want to merge this PR but I have a few questions:

1. Is EVP_ based methods supported for older 1.0.2.x versions where x is lower than version h where you tested? Just to make sure we do not break anybody's code.
2. I saw the flag OPENSSL_FIPS used at the sample codes (http://openssl.6102.n7.nabble.com/APIs-forbidden-in-FIPS-mode-td44106.html), is this an openssl provided flag? I mean can I rely on it? That just for sake of backward compatibility I can have this suggested implementation only when this flag is defined and it would be a safer approach i guess, what do you think?

**Comment by aparnam-asg** [comment]
1. I think so. I see EVP.h in github even for 0.9.6 version. 
2. This code only uses high level API instead of low level. That code should work with or without fips. Internal implementation calls within openssl will be different based on fips is turned on or not. I don't see it as a concern for non fips users.

**Comment by aparnam-asg** [comment]
Did you try the test code that is attached with this ticket on Nov 1st 2017? That was reproducing for me then. First thing it does is turn on fips and then has other code. Not sure if that is what is different between your test and mine.

**Comment by aparnam-asg** [comment]
Also, your openssl library should be built in fips mode. You can find information on how to build here: https://www.openssl.org/docs/fips/UserGuide-2.0.pdf

**Comment by ihsandemir** [comment]
@aparnam-asg Is there a pre-built binary fips library that I can use for CentOS 5 instead of building from scratch?

**Comment by aparnam-asg** [comment]
Not as far as I know, it was built by Justin for our product. @justinpa-asg do you know if there is any such library?

**Comment by justinpa-asg** [comment]
> Is there a pre-built binary fips library that I can use for CentOS 5

Unfortunately no. CentOS 5 includes OpenSSL 0.9.8. 

> The 2.0 FIPS module is compatible with OpenSSL releases 1.0.1 and 1.0.2, and no others.

https://wiki.openssl.org/index.php/FIPS_modules

There is a bintray contributor for OpenSSL 1.0.2 binaries, but not with FIPS.

https://bintray.com/conan-community/conan/OpenSSL%3Aconan/1.0.2p%3Astable#files/conan/OpenSSL/1.0.2p/stable

Perhaps @aparnam-asg can obtain permission to provide just the OpenSSL binaries shipped with our product.

**Comment by justinpa-asg** [comment]
If you want to try your luck with CentOS 6 or Oracle Linux 6, then look here:
https://docs.oracle.com/cd/E37670_01/E36387/html/section_vkp_5rv_wq.html
https://yum.oracle.com/repo/OracleLinux/OL6/addons/x86_64/
https://yum.oracle.com/repo/OracleLinux/OL6/latest/x86_64/

I do not see similar packages for 7, but possibly these will run there too.

**Comment by ihsandemir** [comment]
@justinpa-asg I could not install from those links, my system is CentOS6 and CentOS 7. I am using this docker image: https://hub.docker.com/r/ihsan/centos7_gcc_485_ssl/  Can you try installing in this image and let me know if it works for you?

Meanwhile, I downloaded and compiled fips source code and openssl source code and installed the new installation in my docker image locally but could not generate the problem yet.
