### ISSUE TITLE
Deadlock if use addEntryListener in EntryListener

### ISSUE THREAD

**Issue by wsw2016** [hazelcast/hazelcast-cpp-client#338]
If I open an new map in the EntryListener and add a new EntryListener to it the application hangs.

[main.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/1415766/main.txt)

**Comment by ihsandemir** [comment]
Hello,

You are making hazelcast call inside the entrylistener handleValueChange method. Please try to handle it differently. It sill block the client io thread and a deadlock, that is why we did put this warning: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/include/hazelcast/client/EntryListener.h#L38

Regards,
ihsan

**Comment by ihsandemir** [comment]
Closing the issue since there was no feedback and the solution was provided.
