### ISSUE TITLE
C++ hazelcast client occasionally core dumps in controlledThread during re-connection to hazelcast server

### ISSUE THREAD

**Issue by siwhiting** [hazelcast/hazelcast-cpp-client#353]
hazelcast java server 3.8.2 running java8 on centos-6 running on machine1, which has an IMAP being updated + configuration stored in another IMAP.

hazelcast C++ client 3.8.3 built on centos-6 / 32 bit (also fails with 3.7.0) on machine2.

The client reads configuration from server on start-up, then updates (add/replace) one entry in the IMAP every second. The client, also manages connection re-establishment, by using hazelcast lifecycle disconnect indication (not re-entrant, as event passed on queue).

Script is run on the server that loops forever, do the following:
    1) Stops hazelcast server
    2) waits 1 second
    3) Starts hazelcast server
    4) waits 29-30 seconds (random 0-1 sec)
    
The script was left to run overnight.

In the morning, 4 cores were seen (same backtrace - see attached file) from the hazelcast C++ client.

It seems that the issue relates to the failed? connection establishment attempt in the hazelcast::util::Thread::controlledThread.

Please get back to me, if you require any further information.

Regards,
Simon

**Comment by siwhiting** [comment]
[bt.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/1509081/bt.txt)

**Comment by pirog-spb** [comment]
I have a similar problem with hazelcast C++ client 3.8.3(first seen on 3.6.3).
Stderr output:
```
terminate called after throwing an instance of 'hazelcast::client::exception::IOException'
  what():  ExceptionMessage {Connection closed by remote} at TcpSocket::receive
[1510221275.924508] 57943 signal(6) Aborted, thread:389
```
Backtrace:
```
0# main::{lambda()#1}::_FUN()
1# __cxxabiv1::__terminate(void (*)())
2# std::terminate()
3# __gxx_personality_v0
4# 0x00007F5DB6B7DD1C in ./lib/libgcc_s.so.1
5# _Unwind_Resume in ./lib/libgcc_s.so.1
6# hazelcast::client::connection::Connection::~Connection()
7# hazelcast::client::connection::Connection::~Connection()
8# hazelcast::client::connection::ConnectionManager::connectTo(hazelcast::client::Address const&, bool)
9# hazelcast::client::connection::ConnectionManager::getOrConnectResolved(hazelcast::client::Address const&)
10# hazelcast::client::connection::ConnectionManager::getRandomConnection()
11# hazelcast::client::connection::ConnectionManager::getOrConnect(hazelcast::client::Address const&, int)
12# hazelcast::client::connection::ConnectionManager::getRandomConnection(int, std::string const&, int)
13# hazelcast::client::spi::InvocationService::resend(boost::shared_ptr<hazelcast::client::connection::CallPromise>, std::string const&)
14# hazelcast::client::spi::ServerListenerService::retryFailedListener(boost::shared_ptr<hazelcast::client::connection::CallPromise>)
15# hazelcast::client::spi::InvocationService::cleanEventHandlers(hazelcast::client::connection::Connection&)
16# hazelcast::client::spi::InvocationService::cleanResources(hazelcast::client::connection::Connection&)
17# hazelcast::client::connection::Connection::close(char const*)
18# hazelcast::client::connection::IOHandler::handleSocketException(std::string const&)
19# hazelcast::client::connection::ReadHandler::handle()
20# hazelcast::client::connection::InSelector::listenInternal()
21# hazelcast::client::connection::IOSelector::listen()
22# hazelcast::util::Thread::controlledThread(void*)
23# 0x00007F5DB6959E0F in ./lib/libpthread.so.0
24# clone in ./lib/libc.so.6
```
May be an exception been thrown from destructor when already handling another exception? That's why the "std::terminate()" called

**Comment by ihsandemir** [comment]
This should be fixed by PR https://github.com/hazelcast/hazelcast-cpp-client/pull/392
