### ISSUE TITLE
Decrement Pending packets for events also

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-cpp-client#4]
An issue found in java client.
https://github.com/hazelcast/hazelcast/pull/6608
Needs to be checked if same issue is here.

**Comment by ihsandemir** [comment]
This is most probably fixed with test PR https://github.com/hazelcast/hazelcast-cpp-client/pull/392

Will duplicate the Java test testPendingEventPacketsWithEvents to verify.

**Comment by ihsandemir** [comment]
We decided to remove pendingPacketCount completely from Java client as well. The removal PR is: https://github.com/hazelcast/hazelcast/pull/13221/files

Hence, we will do the same for cpp client as well.
