### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by ahmeterbay** [hazelcast/hazelcast-cpp-client#415]
hi..
can i help you to design a new logo for your application?
it will be free :)

**Comment by ihsandemir** [comment]
This is a spam issue.

**Comment by ahmeterbay** [comment]
ihsan neden spam yazdın ki-- spam değilim birader.. logo tasarlıyorum ben. birçok kişiyede tasarladım.. son 10 gündür iş yogunlugundan github a gırıp bakmadım.. spam demişsiniz.. vaybea
