### ISSUE TITLE
C++ client crashes in ClientConnectionManagerImpl::ShutdownTask::getName() when connection is shutdown

### ISSUE THREAD

**Issue by siwhiting** [hazelcast/hazelcast-cpp-client#428]
hazelcast java server 3.8.2 running java8 on centos-6 on machine1
hazelcast C++ client 3.10-BETA-1 running on centos-6 / 32 bit on machine2.

After client successfully establishes connection to server. Run tcpkill on machine1 on the established connection port (also seen occasionally when stopping the hazelcast server).

Following core stack trace is seen using tcpkill:

Program terminated with signal 6, Aborted.
#0  0x00f6b430 in __kernel_vsyscall ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.i686 keyutils-libs-1.4-5.el6.i686 krb5-libs-1.10.3-42.el6.i686 libcom_err-1.41.12-22.el6.i686 libgcc-4.4.7-16.el6.i686 libpcap-0.9.4-15.el5.i386 libselinux-2.0.94-5.8.el6.i686 libstdc++-4.4.7-16.el6.i686 openssl098e-0.9.8e-20.el6.centos.1.i686 zlib-1.2.3-29.el6.i686
(gdb) bt
#0  0x00f6b430 in __kernel_vsyscall ()
#1  0x02cd0781 in raise () from /lib/libc.so.6
#2  0x02cd205a in abort () from /lib/libc.so.6
#3  0x00931b87 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/libstdc++.so.6
#4  0x0092f9e6 in ?? () from /usr/lib/libstdc++.so.6
#5  0x0092fa23 in std::terminate() () from /usr/lib/libstdc++.so.6
#6  0x0092fb6b in __cxa_throw () from /usr/lib/libstdc++.so.6
#7  0x008d0960 in std::__throw_length_error(char const*) () from /usr/lib/libstdc++.so.6
#8  0x0090cef6 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned int, unsigned int, std::allocator<char> const&) ()
   from /usr/lib/libstdc++.so.6
#9  0x0090e029 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_clone(std::allocator<char> const&, unsigned int) ()
   from /usr/lib/libstdc++.so.6
#10 0x0090e167 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/libstdc++.so.6
#11 0x007205e7 in hazelcast::client::connection::ClientConnectionManagerImpl::ShutdownTask::getName() const () from /opt/engine/lib/libHazelcastClient3.10-BETA-1_32.so
#12 0x08183995 in hazelcast::util::Thread::runnableThread (args=0xeaeb24d8) at ../target/deps/hazelcast-cpp-client-3.10-BETA-1/include/hazelcast/util/PosixThread.inl:81
#13 0x00df1bc9 in start_thread () from /lib/libpthread.so.0
#14 0x02d8904e in clone () from /lib/libc.so.6

Following core stack trace is seen occasionally when stopping the hazelcast server:

Program terminated with signal 11, Segmentation fault.
#0  0x007963f0 in __memcpy_ssse3_rep () from /lib/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.i686 keyutils-libs-1.4-5.el6.i686 krb5-libs-1.10.3-42.el6.i686 libcom_err-1.41.12-22.el6.i686 libgcc-4.4.7-16.el6.i686 libpcap-0.9.4-15.el5.i386 libselinux-2.0.94-5.8.el6.i686 libstdc++-4.4.7-16.el6.i686 openssl098e-0.9.8e-20.el6.centos.1.i686 zlib-1.2.3-29.el6.i686
(gdb) bt
#0  0x007963f0 in __memcpy_ssse3_rep () from /lib/libc.so.6
#1  0x003d206e in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_clone(std::allocator<char> const&, unsigned int) ()
   from /usr/lib/libstdc++.so.6
#2  0x003d2167 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/libstdc++.so.6
#3  0x00b225e7 in hazelcast::client::connection::ClientConnectionManagerImpl::ShutdownTask::getName() const () from /opt/engine/lib/libHazelcastClient3.10-BETA-1_32.so
#4  0x08183995 in hazelcast::util::Thread::runnableThread (args=0xf2615010) at ../target/deps/hazelcast-cpp-client-3.10-BETA-1/include/hazelcast/util/PosixThread.inl:81
#5  0x0018cbc9 in start_thread () from /lib/libpthread.so.0
#6  0x0074104e in clone () from /lib/libc.so.6

**Comment by ihsandemir** [comment]
Can you also do info threads and share with us the stack traces of other outstanding threads while this occured? (Change to each thread and print stack traces: e.g. thread 5; bt )

**Comment by ihsandemir** [comment]
I think your client went out of scope somehow and hence the client is destructed before the the thread that runs the ShutdownTask terminated which may cause this problem.

**Comment by siwhiting** [comment]
[issue_428_info_threads.txt](https://github.com/hazelcast/hazelcast-cpp-client/files/2110739/issue_428_info_threads.txt)

**Comment by ihsandemir** [comment]
@siwhiting Can you share with me the tcpkill command that you use to reproduce the issue?
