### ISSUE TITLE
External boost::shared_ptr support

### ISSUE THREAD

**Issue by SX91** [hazelcast/hazelcast-cpp-client#474]
It would be nice to support Boost include dirs override. For example:
```
if (HZ_EXTERNAL_BOOST)
    find_package(Boost REQUIRED)
    include_directories(${Boost_INCLUDE_DIRS})
else ()
    include_directories(SYSTEM ${PROJECT_SOURCE_DIR}/external/include/)
endif(HZ_EXTERNAL_BOOST)
```

**Comment by ihsandemir** [comment]
Hello, it can be done. Did current version caused any problems like version compatibility, etc?

**Comment by SX91** [comment]
@ihsandemir I'm using hazelcast cpp client as conan package (with many others packages depending on Boost). I can easily override Boost version with any new/old one, same with asio, so all of my dependencies would be compiled with same Boost version.

> Did current version caused any problems like version compatibility, etc?

Can't provide such info, but I had some compatibility problems with shared_ptr (compiled one module with 1.66.0, another with 1.5X.0, the system one).

**Comment by ihsandemir** [comment]
Ok, I see. I think we can do this since there is a need for it. 

Did you package Hazelcast for conan? Are there any code changes you needed to make the conan package?

**Comment by SX91** [comment]
> Ok, I see. I think we can do this since there is a need for it.

Thank you!

> Did you package Hazelcast for conan? Are there any code changes you needed to make the conan package?

Not really. I've written [the basic recipe](https://gist.github.com/SX91/f2fe703760376db4ec8d05466cc8bd57) for hazelcast-cpp-client, but didn't polish it enough nor covered all possible cmake options there.

**Comment by SX91** [comment]
Oops, not quite. With `HZ_BUILD_WITH_SSL` option turned on, some includes for `asio/asio/include/asio/ssl/*` get activated. So if I override asio path, compilation fails.

**Comment by ihsandemir** [comment]
I just merged the PR to master. Can you please try and let me know?

**Comment by ihsandemir** [comment]
> > Ok, I see. I think we can do this since there is a need for it.
> Not really. I've written [the basic recipe](https://gist.github.com/SX91/f2fe703760376db4ec8d05466cc8bd57) for hazelcast-cpp-client, but didn't polish it enough nor covered all possible cmake options there.
> 
Does this recipe handle Windows and MAC OS builds at all? Windows library names are totally different.

**Comment by ihsandemir** [comment]
@SX91 Were you able to try the master branch with your setup and verify that the fix actually works for you? I am eager to hear on the result.

**Comment by ihsandemir** [comment]
I am closing this issue since I did not get  feedback for a while, please feel free to reopen if the problem still exists.

**Comment by SX91** [comment]
@ihsandemir Hello! Sorry for the delay.
Looked through the changes. Yes, options are fixed now, but can't see external boost library support there.

**Comment by ihsandemir** [comment]
Yes, you are correct, I forgot to add the options to cmake file. I will send a PR for that. Thanks.

**Comment by SX91** [comment]
@ihsandemir the fix at #490 looks good! Thank you!

**Comment by SX91** [comment]
@ihsandemir hello!
Latest release (3.11.0) doesn't include ASIO in archive (the directory at `external/include/asio` is empty).
`external/include` directory structure is too error-prone. You've introduced new dependency `easylogging++` and placed it under `external/include` directory, but that directory is included only if `HZ_FIND_EXTERNAL_BOOST` is set to `OFF`.

Maybe the better structure would be `external/<DEP_NAME>/include/<...>`?

**Comment by ihsandemir** [comment]
hello @SX91 we now have the conan integration PR almost ready to be merged to conan center https://github.com/conan-io/conan-center-index/pull/4452
