### ISSUE TITLE
Conflict ClientMessage.h with mysql-dev

### ISSUE THREAD

**Issue by skyend** [hazelcast/hazelcast-cpp-client#518]
I found a conflict thing.

static const uint8_t `PROTOCOL_VERSION` in `hazelcast/client/protocol/ClientMessage.h:111`

It conflict with defined Macro In `mysql/mysql_version.h` in `mysql-dev (5.7.25)`

**Comment by burakcelebi** [comment]
Many thanks @skyend for raising this issue with your PR! 👏 :)
