### ISSUE TITLE
Missing API HazelcastClient::getLocalEndpoint()

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-cpp-client#524]
We are missing the Java client API `HazelcastClient.newHazelcastClient(clientConfig).getLocalEndpoint().getUuid();` so that the users can get client UUID.

This request came from community:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hazelcast/5ENDW4ffxPg/ibO0eomoGQAJ

**Comment by burakcelebi** [comment]
Thanks Ihsan! Marked this as a high priority.

Let me add your note from your GoogleGroups message:

> Meanwhile, here is a hacky workaround (The interfaces here can change since they are not public API but can work for you until we release the next version):
> 
> ```
> spi::ClientContext clientContext(client);
> boost::shared_ptr<protocol::Principal> principal = clientContext.getConnectionManager().getPrincipal();
> if (principal.get()) {
>     std::string uuid = *principal->getUuid();
> }
> 
> ```
> Do not forget the appropriate includes:
> ```
> #include <hazelcast/client/HazelcastClient.h>
> #include <hazelcast/client/connection/ClientConnectionManagerImpl.h>
> ```
