### ISSUE TITLE
Missing "LOADED" event

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-cpp-client#551]
See https://github.com/hazelcast/hazelcast-go-client/issues/464

IMDG 3.11 added LOADED event - https://docs.hazelcast.org/docs/3.12.1/javadoc/com/hazelcast/core/EntryEventType.html#LOADED

This is not handled by this client

**Comment by enozcan** [comment]
Can I take care of this if no one else already did?

**Comment by burakcelebi** [comment]
Sure @enozcan, please go ahead! :) This is the corresponding Java issue, as far as I know: https://github.com/hazelcast/hazelcast/issues/13667

cc: @ihsandemir

**Comment by enozcan** [comment]
Sorry for not being able to complete the PR. I'm unassigning myself to let someone else to do so.

**Comment by ihsandemir** [comment]
@neilstevenson  We added this event to the list of events. Hence, it is supported now. Closing the issue. Please re-open if further problems/questions.
