### ISSUE TITLE
Cpp API to connect to a Jet member

### ISSUE THREAD

**Issue by yigitmultibankfx** [hazelcast/hazelcast-cpp-client#565]
I was directed to hazelcast cpp client by Vladimir Schreiner with his following reply to one of my questions on the hazelcast github issues feed:
"Jet cluster has multiple APIs. The Pipeline API and DAG API (used to define and execute streaming jobs) can be used just via Java client.
You can use the C++ client for the data storage APIs. The data insertion stage can use C++ client to push the data to Jet cluster. The streaming job picks it from the storage."

So I think this reply means I can connect to a jet member with the cpp api. Now when I use the default configuration to connect to a jet member, I am getting an authentication error altough I set no credentials for client setup. I am actually using the very basic code sample that defines a client and gets a map out of it.

Instead, when I setup an IMDG member, the code sample seems to work. Am I doing something wrong, or did I misunderstand Vladimir's message?

Kind Regards

**Comment by yigitmultibankfx** [comment]
this basically solved my problem, thank you !

**Comment by ihsandemir** [comment]
Closing the issue.
