### ISSUE TITLE
PagingPredicate with PortableFactory

### ISSUE THREAD

**Issue by yigitmultibankfx** [hazelcast/hazelcast-cpp-client#566]
Should the PagingPredicate normally work fine with a PortableFactory?
Cause currently I am getting the "HazelcastSerializationException {Could not find PortableFactory for factory-id: 1." exception when I try to use a very simple PagingPredicate with only predicateSize provided for its constructor. and even though the serialization and deserialization of the particular class works fine normally (if I fail to register the factory those should have failed as well but I am able to printf the contents of the IMap), when the predicate is used, it crashes with the above exception.

**Comment by yigitmultibankfx** [comment]
The attached files are: the code that crashes and the output screen. As you can clearly see, the current client config includes a portable factory with id: 1 (see the first line in the output screen where I print it) but the code still throws an exception saying there is no factoryId:1, when I run a query with a PagingPredicate.
![err_code1](https://user-images.githubusercontent.com/54355441/65136152-bf475b00-da0f-11e9-80b9-6e9be85a8763.jpg)
![err_out1](https://user-images.githubusercontent.com/54355441/65136153-bfdff180-da0f-11e9-9145-bfe5cae34214.jpg)

**Comment by ihsandemir** [comment]
@yigitmultibankfx Yes, it should just work. When you do query with portables, then the portable needs to be deserialized at the server side and hence you need to register the portable factory at the server side as well. Did you configure server side with the portable factory? The exception came from the server side with a java stack trace indicating that the server could not deserialize. Can you try configuring the server side and try again?

Note: It would be much useful for other people also if we can carry these kind of question discussions to Hazelcast google group, https://groups.google.com/forum/#!forum/hazelcast, so that other people can benefit from our findings as well.

**Comment by yigitmultibankfx** [comment]
@ihsandemir Could you please check my second message which shows the details of my code? I should be registering the factory properly since I am able to print the contents of the map, and besideswhen I get the portablefactory map from the client config after I connect to the cluster, the id of the first and only portable factory is already 1.

**Comment by ihsandemir** [comment]
@yigitmultibankfx Yes, I saw your code. It looks good for client side. I am talking about server side configuration. The server also needs to know how to deserialize and compose your object in Java for the PagingPredicate type query. For most queries, this may not be needed but for PagingPredicate, the retrieved values needs to be sorted before returning a page to the user. Hence, you can see it in the Java stack trace calls that it needs deserialization for sorting. Therefore, you need to register the portable factory at the server side.

**Comment by yigitmultibankfx** [comment]
That is the point I am trying to make. I am **already** doing that. Please check my code carefully. If I wasn't doing that, how would the hazelcast client instance be able to print "factoryid : 2" from its serialization configuration ?
Here is the line I make the registeration:

xconfig.getSerializationConfig().addPortableFactory(MT4PortableFactory::FACTORY_ID,
			boost::shared_ptr<serialization::PortableFactory>(
				new MT4PortableFactory()));

**Comment by ihsandemir** [comment]
@yigitmultibankfx I am talking about **SERVER** side configuration, I did not see any code or xml config for server side config in the code you shared. At the server side, you need Java implementation of the same class. Does this make sense?

**Comment by yigitmultibankfx** [comment]
I got you know. The reference manual you directed me is for Hz IMDG. Does it also work for a jet cluster?

**Comment by yigitmultibankfx** [comment]
I am now able to load the factory in the java server side. still getting the same error. is there a sample or any kind of documentation that describes how to use a portable factory with a paging predicate in c++?

**Comment by yigitmultibankfx** [comment]
Solved all of these for now. Thanks.

**Comment by ihsandemir** [comment]
@yigitmultibankfx I am happy to hear that you were able to solve the problem. Yes, we have code samples. The PagingPredicate example is here: https://github.com/hazelcast/hazelcast-cpp-client/blob/master/examples/distributed-map/query/queryExample.cpp#L191  Server side part of the cod is not here but you can see an example here at Java code samples: https://github.com/hazelcast/hazelcast-code-samples/blob/master/distributed-map/paging-predicate/  Java sample uses Java serialization for simplicity hence it may not fit your case but you can check this Java sample to understand how you can configure your portable at the Java server side: https://github.com/hazelcast/hazelcast-code-samples/tree/master/serialization/portable  Especially, look at the config xml here: https://github.com/hazelcast/hazelcast-code-samples/blob/master/serialization/portable/src/main/resources/hazelcast.xml#L9 This is how it is configured using xml.

Let me know any further questions and I also wonder how you were able to solve the problem. I would appreciate if you can share your solution as well.

**Comment by dbrimley** [comment]
Is this ready to close now?

**Comment by ihsandemir** [comment]
> Is this ready to close now?

@dbrimley Yes, it seems to be solved since no further problems are reported. Closing the issue.
