### ISSUE TITLE
CMake Infrastructure relies on default GCC build bits

### ISSUE THREAD

**Issue by alexvanzu** [hazelcast/hazelcast-cpp-client#567]
C++ compiler version: GCC 7.2
Hazelcast Cpp client version: Master GitHub Cline
Hazelcast server version: N/A
Number of the clients: N/A
Cluster size, i.e. the number of Hazelcast cluster members:
OS version (Windows/Linux/OSX): Linux

Please attach relevant logs and files for client and server side.

#### Expected behaviour
The build of the 64 bit client is explicit called as part of the cmake infrastructure

#### Actual behaviour
the cmake infrastructure sets only only the -m32 option if it is building the 32 bits and relies on the gcc default behaviour for the 64 and doesn't perform any check at the end of build on the output archive / shared object to ensure it is a 64 bits build (even if in the name there is the 64)

#### Steps to reproduce the behaviour
Build with 64 bit option, the gcc is not invoked with the -m64

**Comment by ihsandemir** [comment]
Is your environment a 32-bit built machine? Because the default for the option if nothing provided is the same as your environment.

But in any case, we can force it to use -m64 for 64-bit as you suggested. I will send a PR for that.

Thanks for the contribution.

**Comment by ihsandemir** [comment]
@alexvanzu Can you please review the fix PR https://github.com/hazelcast/hazelcast-cpp-client/pull/568 ?
