### ISSUE TITLE
Missing tryLock with leaseTime option for IMap

### ISSUE THREAD

**Issue by enozcan** [hazelcast/hazelcast-cpp-client#579]
Currently, client supports `tryLock` with `timeToWait` or no time restriction at all for IMap. 
Per [implementation](https://github.com/hazelcast/hazelcast/blob/8f5f00237c900632ec0783b5ad211e047b7dff64/hazelcast/src/main/java/com/hazelcast/map/IMap.java#L1918), setting `leaseTime` is also possible and seems like it's missing in the client impl. It would be useful to include that in cpp client as well.

**Comment by burakcelebi** [comment]
Many thanks for your contributions @RikeVoltz!! :)

**Comment by RikeVoltz** [comment]
I am glad to help and thank you for this great project and for the opportunity to participate in its development, @burakcelebi  :)

**Comment by burakcelebi** [comment]
Hey @RikeVoltz, we cannot make it without the fantastic Hazelcast community members like you! 🥇🥇🥇 

Also, many thanks to our lead C++ Engineer @ihsandemir for his support throughout the process. 💯
