### ISSUE TITLE
Behaviour of client when cluster is shutdown

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-cpp-client#59]
We need to check how the client behave when the cluster is down. Should it retry connecting to the configured ip addresses as it does on startup, or what? 

Currently,when the last member goes down since no cluster update is received the last server exist in the member list and it is the only one tried for connections, is this correct behaviour?

**Comment by sancar** [comment]
In clusterListenerThread when client tries to open a new connection back to cluster it calls the following method to get addresses that needs to be retried.

```
            std::vector<Address> ClusterListenerThread::getSocketAddresses() {
                std::vector<Address> addresses;
                if (!members.empty()) {
                    std::vector<Address> clusterAddresses = getClusterAddresses();
                    addresses.insert(addresses.begin(), clusterAddresses.begin(), clusterAddresses.end());
                }
                std::vector<Address> configAddresses = getConfigAddresses();
                addresses.insert(addresses.end(), configAddresses.begin(), configAddresses.end());
                return addresses;
            }
```

From here, we can see that it loads the config addresses along with the last address it knows. And this is the expected behaviour.
