### ISSUE TITLE
Version API

### ISSUE THREAD

**Issue by andysCaplin** [hazelcast/hazelcast-cpp-client#612]
Hazelcast Cpp client version: 3.12

Is there an API to query the library version ? I can't find one in the headers. 

Nearest I can find is the BuildInfo class but when I tried to use the API in that I get a crash.

**Comment by ihsandemir** [comment]
Hello @andysCaplin we currently do not provide a public API to provide the client version but it is really being kept inside the logger as private member: https://github.com/hazelcast/hazelcast-cpp-client/blob/v3.12/hazelcast/include/hazelcast/util/ILogger.h#L89 and it is being printed for all the log statements. We provide this parameter to cmake during the build process as a definition here: https://github.com/hazelcast/hazelcast-cpp-client/blob/v3.12/CMakeLists.txt#L39  and pass this to the logger.

The API can be added very easily. I am putting it to 4.0 release milestone as a feature request.

Well, you can do a work around to obtain the version by parsing the log line. The client always prints logs on startup, you can obtain the `stdout` stream (by redirecting to example stringstream https://stackoverflow.com/questions/5419356/redirect-stdout-stderr-to-a-string) and parse it to get the version string.

**Comment by andysCaplin** [comment]
Thank you.
