### ISSUE TITLE
Should we separate client start from client construction?

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-cpp-client#656]
Current situation: Client is started immediately on construction and the constructor can throw exceptions.
```
HazelcastClient c;

```
Alternative: Construction does not start the client. We start the client with connect call. The client can not reconnect. connect can throw.
```
HazelcastClient c;
c.connect();
```

Pros:
- Constructor can be marked as noexcept.

Cons:
- User code lines from 1 to 2 lines to start a client.

**Comment by yemreinci** [comment]
> Constructor can be marked as noexcept.
HazelcastClient holds a pointer to implementation. So the ctor can still throw exceptions.

**Comment by ihsandemir** [comment]
After brief discussion, I decided not to change the current API. We can later add static factory methods if any request comes.
