### ISSUE TITLE
Logging comment

### ISSUE THREAD

**Issue by andysCaplin** [hazelcast/hazelcast-cpp-client#682]
Just noticed this while browsing the latest code in master

```
./hazelcast/src/hazelcast/logger.cpp:          << HAZELCAST_VERSION << "] [" // TODO once we have an API for the library version, use that instead
```

There is an API for the library version now - [#657](https://github.com/hazelcast/hazelcast-cpp-client/pull/657)

**Comment by ihsandemir** [comment]
yes, this can be changed, thanks for the review. would you like to send a PR for it? (one line PR:) )
