### ISSUE TITLE
Confusion regarding versioning

### ISSUE THREAD

**Issue by jackrevell** [hazelcast/hazelcast-cpp-client#699]
According to the official repository releases the latest version is 3.12.1 https://github.com/hazelcast/hazelcast-cpp-client/releases, however in CMakeLists.txt it appears the "VERSION" is set to 4.0. Is the version listed in CMakeLists.txt in fact an alpha version? The last official release as per the link above was in January, however considerable work has been done on the repo since then - would it be possible to have some clarification regarding this apparent discrepancy in versions?

**Comment by ihsandemir** [comment]
Hello, current master branch is the development branch, hence it is actually 4.0-SNAPHOT version at the moment which will become 4.0 version when released. The 3.12.1 version details are at the 3.12.1 tag at https://github.com/hazelcast/hazelcast-cpp-client/tree/v3.12.1 . At this tag, you can see that the version in `CMakeLists.txt`  is 3.12.1 (https://github.com/hazelcast/hazelcast-cpp-client/blob/v3.12.1/CMakeLists.txt#L31)

Is this explanation clear?

**Comment by ihsandemir** [comment]
@jackrevell Is the above explanation clear enough for you? If no further questions, I would like to close this issue.

**Comment by ihsandemir** [comment]
Closing this issue. Please feel free to reopen if still have questions in mind. Thanks.
