### ISSUE TITLE
LoadTest.testIntMapDummyClientServerRestart sometimes fails on Windows

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-cpp-client#84]
LoadTest.testIntMapDummyClientServerRestart sometimnes fails on Windows.

```
00:46:31 C:\jenkins\ope-fs-root\workspace\cpp_windows - maintenance - nightly\hazelcast\test\src\faulttolerance\LoadTest.cpp(61): error: Expected: val = map->get(i) doesn't throw an exception.
00:46:31   Actual: it throws.
```

https://hazelcast-l337.ci.cloudbees.com/job/cpp_windows%20-%20maintenance%20-%20nightly/83/consoleFull

https://hazelcast-l337.ci.cloudbees.com/job/cpp-linux-nightly-32-SHARED-Debug/121/testReport/junit/(root)/LoadTest/testIntMapDummyClientServerRestart/

**Comment by hasancelik** [comment]
```
C:\jenkins\ope-fs-root\workspace\cpp_windows - maintenance\hazelcast\test\src\faulttolerance\LoadTest.cpp:61
Expected: val = map->get(i) doesn't throw an exception.
  Actual: it throws.
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/cpp_windows%20-%20maintenance/669/testReport/junit/(root)/LoadTest/testIntMapDummyClientServerRestart/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/cpp-windows-maintenance/690/testReport/junit/(root)/LoadTest/testIntMapDummyClientServerRestart/

**Comment by ihsandemir** [comment]
This is duplicate of issue #227
