### ISSUE TITLE
Test executable crashes when running ReliableTopicTest

### ISSUE THREAD

**Issue by yemreinci** [hazelcast/hazelcast-cpp-client#873]
The test executable occasionally crashes on GA while executing the tests under the suite `ReliableTopicTest`. 

Here is a run that crashed: https://github.com/hazelcast/hazelcast-cpp-client/runs/2559526252?check_suite_focus=true

**Comment by ihsandemir** [comment]
Can you also attached the stack trace and log here in case the GA build log is lost?

**Comment by yemreinci** [comment]
> Can you also attached the stack trace and log here in case the GA build log is lost?

[2_Ubuntu-x86_64 (Debug, Static, SSL).txt](https://github.com/hazelcast/hazelcast-cpp-client/files/6464645/2_Ubuntu-x86_64.Debug.Static.SSL.txt)

**Comment by hakanaktas0** [comment]
Related to [#852](https://github.com/hazelcast/hazelcast-cpp-client/issues/852)

**Comment by akeles85** [comment]
Solved with PR #1071
