### ISSUE TITLE
C++ 17 vs C++ 11 incompatibility

### ISSUE THREAD

**Issue by wsw2016** [hazelcast/hazelcast-cpp-client#895]
C++ compiler version: 9.3.0
Hazelcast Cpp client version: 4.1.1
Hazelcast server version: 4.2
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 1
OS version (Windows/Linux/OSX): Ubuntu 20.04

#### Expected behaviour
Normally the Cpp-client is compiled with C++-11 version. With earlier versions it could then be used in C++17 code.

#### Actual behaviour
Now the compiling terminates with an error "multiple definition of hazelcast::client::imap::UNSET".

#### Steps to reproduce the behaviour
Change in examples/CMakeLists.txt the CMAKE_CXX_STANDARD 17
and try to compile with BUILD_EXAMPLES=ON and BUILD_SHARED_LIBS=OFF

**Comment by yemreinci** [comment]
Hello @wsw2016, thanks for reporting this. I was able to reproduce it on Ubuntu 20.04 as you described. For a quick solution, you can do **one** of the followings:

- Increase the C++ standard for the library as well. You can do this by changing the `set(CMAKE_CXX_STANDARD 11)` line in the topmost CMakeLists.txt file to `17`.
- Or, comment out line 53 in `hazelcast-cpp-client/hazelcast/src/hazelcast/client/proxy.cpp` and rebuild:
```c++
        // constexpr std::chrono::milliseconds imap::UNSET;
```

Both fixed the error for me. 

We will investigate more and try to come up with a better solution.  

**Additional information:** I have also tested with Clang 11 on Ubuntu and it compiled without errors.
