### ISSUE TITLE
Hazelcast cpp client does not read a hazelcast.xml config file

### ISSUE THREAD

**Issue by rthomaskelly** [hazelcast/hazelcast-cpp-client#914]
C++ compiler version: NA
Hazelcast Cpp client version: >=4.0.0
Hazelcast server version: NA
Number of the clients: NA
Cluster size, i.e. the number of Hazelcast cluster members: NA
OS version (Windows/Linux/OSX): NA

#### Expected behaviour
[The docs](https://github.com/hazelcast/hazelcast-cpp-client/blob/v4.1.1/Reference_Manual.md#141-configuring-hazelcast-imdg) describe the C++ client reading a "hazelcast.xml" config upon start up. I do not see this happening. I don't see code that is looking for a "hazelcast.xml" file outside of the test/ dir. I see a read_from_xml_file() fn in the test/ dir, but I don't see any code to take a parsed xml file and convert it into the C++ hazelcast client config object.

#### Actual behaviour
It does not appear any hazelcast.xml config is read. The only hazelcast.xml file in the repo is in test/resources. It only appears to be read by a couple test programs, one of which sends the config to the remote server (it isn't actually converted into the C++ config object).

#### Other
The Java clients are able to read a .yaml file. It would be great if the C++ client could use a YAML file also because then configurations could be shared between the Java & C++ clients.

**Comment by ihsandemir** [comment]
Hello @rthomaskelly C++ client is currently only configurable programatically. We had plans for adding such support for yaml and xml but did not get planned as of yet. See [issue 329](https://github.com/hazelcast/hazelcast-cpp-client/issues/329)

By the way, the hazelcast.xml that you see in the test folders are configurations of the hazelcast server itself. The client side configuration is usually named similar to hazelcast-client.xml and it is different from server configuration. We can do something similar to the Java client configurations.

I will ask the Product Management if we can schedule this request.

Can you provide more information of your use case? Do you have Java and C++ client running in the same cluster environment? Do they have to have exact same config files?

**Comment by rthomaskelly** [comment]
Yes, the use case in C++ is really the same as it is in Java. We want to configure our apps to connect to a established clusters in various manners without re-building the app. In our case it would be best if the configs match so they are agnostic to Java/C++ apps because the clients connect to the same cluster cluster.

May I also recommend that you ought to remove the section in the C++ client docs speaking of config files because it is currently incorrect and feeling dishonest.

**Comment by ihsandemir** [comment]
> Yes, the use case in C++ is really the same as it is in Java. We want to configure our apps to connect to a established clusters in various manners without re-building the app. In our case it would be best if the configs match so they are agnostic to Java/C++ apps because the clients connect to the same cluster cluster.
> 
> May I also recommend that you ought to remove the section in the C++ client docs speaking of config files because it is currently incorrect and feeling dishonest.

Are you referring to `hazelcast.xml` referrals in the [Reference Manual](https://github.com/hazelcast/hazelcast-cpp-client/blob/master/Reference_Manual.md#141-configuring-hazelcast-imdg) ? Well, they are for the server side configurations and they actually do work when starting the server. I am sorry that it caused a misunderstanding as if it was supposed to work for the C++ client itself. I wonder what can we do it to make it more obvious, do you have any suggestions? We have them in these sections since it is related to the server configuration and removing it would not be very helpful either.

**Comment by rthomaskelly** [comment]
Ah. I see.

Yes, good question. The two neighboring sections mention configuring an "IMDG" vs. a "Client". That distinction isn't so clear to the less initiated like myself (isn't the whole system an IMDG?). I would recommend:
 - Change 1.4.2's intro from "You can configure Hazelcast C++ Client programatically."
   to "You must configure a Hazelcast C++ Client programatically. Config files of any type are not yet supported."
 - It may be better to title 1.4.1 "Configuring a Hazelcast server cluster". 

Thanks for your reply!
