### ISSUE TITLE
Example member configs for authentication are incorrect [API-1080]

### ISSUE THREAD

**Issue by yemreinci** [hazelcast/hazelcast-cpp-client#944]
The XML config examples for [token authentication](https://github.com/hazelcast/hazelcast-cpp-client/blob/master/Reference_Manual.md#5102-token-authentication) and [username-password authentication](https://github.com/hazelcast/hazelcast-cpp-client/blob/master/Reference_Manual.md#5101-username-password-authentication) are incorrect:

1. The example for username password authentication should include a `<member-authentication>` option to work.
2. There is no way to configure token authentication without writing Java code.

**Comment by ihsandemir** [comment]
fixed by https://github.com/hazelcast/hazelcast-cpp-client/pull/1011
